### ISSUE TITLE
combineLatest blocking on completed observables

### ISSUE THREAD

**Issue by brucou** [Reactive-Extensions/RxJS#1036]
I am not sure whether this is an issue or not and it is certainly an edge case. It turns out that when you call `Rx.Observable.combineLatest` with an array of observables, some of which being already completed, nothings is emitted. Looking up the implementation it seems like `combineLatest` is waiting to have at least one value for every source before emitting a value.

What would help is to have a function on a `Rx.Observable` called isCompleted and returns true when the source is completed, so that we can avoid that case programatically. Or maybe the least effort is to document the behaviour of combineLatest in that edge case.

**Comment by rozele** [comment]
The semantics of `Rx.Observable.combineLatest` are to send an OnCompleted event only after all input observables send an OnCompleted event.  The trouble with sending an OnCompleted event immediately when one of the inputs to `combineLatest` is "empty" is that `combineLatest` is also expected to propagate errors from any of the input sequences.  So, if we have...

1st Observable (o1):  ---onNext(1)---onError(ex)
2nd Observable (o2): ---onCompleted()

The expected output of o1.combineLatest(o2) is:
------onError(ex)

If we had terminated the sequence just because o2 is empty, we would never observe the error in o1.

If I were to guess, to get the behavior you're seeking, you may want to consider using `Rx.Observable.takeUntil` and `Rx.Observable.isEmpty` on your input observables and effectively cancel all the inputs if any of the other inputs are empty, e.g.:

o1.takeUntil(o2.isEmpty().filter(identity)).combineLatest(o2.takeUntil(o1.isEmpty().filter(identity)))

**Comment by brucou** [comment]
Interesting. 

1. Does `isEmpty` allows to detect completed observables AFTER they have completed, i.e. called `onCompleted` from their observers? That would be great.

2. The naively expected behaviour IMO of `combineLatest` with completed sources, would be for example with two sources `S1::Observable T1`, `S2::Observable T2`, `S1` being completed, to turn `(Observable T1, Observable T2)` into `Observable (undefined, T2)`. So when S2 emits, we still have a tuple emitted instead of the present blocking behaviour. The blocking behaviour makes sense of course, if there is values in S1 that we have to wait for, but if S1 is completed, then I would have expected to output the values of S2. I agree that the other option which is to complete `combineLatest (S1, S2)` when `S1` completes is problematic vs. `combineLatest` semantics.

**Comment by rozele** [comment]
1. I guess that depends on the implementation of the observable sequence.  The "usual" channels of creating a hot observable, such as creating a subject or using .publish() will "replay" the terminal message (i.e., onError or onCompleted), but there is no such guarantee in general. I would argue though that any hot sequence that did not have this terminal message replay violates the contract of an observable, and appropriate bugs should be filed.

2. It seems like you could achieve this by using a query that returns undefined if the sequence is empty, e.g.:

  observable.isEmpty().filter(identity).map(function(x) { return undefined; })

Doing a combineLatest over such a query would have the output you expect above, producing a tuple of (undefined, T2).

**Comment by brucou** [comment]
Terrific. Thanks for the information. I subsequently close the issue.
