### ISSUE TITLE
Strange behavior of `filter()`

### ISSUE THREAD

**Issue by NXTaar** [Reactive-Extensions/RxJS#1187]
Here is the code. It just an example, which shows the thing.
```javascript
let source = new Rx.Subject();

let threadStorage = {};

let item = {
  apiType: 'thread',
  apiResponse: {
    items: [1,2,3,4,5,6]
  },
  clientInfo: {clientId: '230dsn43', searchWord: 'hello world'}
};

var firstTimeThreadResponse = source.filter(i => i.apiType == 'thread')
                                    .filter(i=> !(i.clientInfo.clientId in threadStorage));
                                   
firstTimeThreadResponse.subscribe(x => {
    console.log(1);
});

firstTimeThreadResponse.subscribe(x => {
    console.log(2);
});
```

The output of this code will be
```
// 1
// 2
```
and that's ok.

BUT. If add some interaction of the item with the outside object like this:
```javascript
firstTimeThreadResponse.subscribe(x => {
    console.log(1);
    threadStorage[x.clientInfo.clientId] = 'foo';
});

firstTimeThreadResponse.subscribe(x => {
    console.log(2);
});
```
The output will give only `1` and looks like the second subscription is never fired.
If we rearrange them like this
```javascript
firstTimeThreadResponse.subscribe(x => {
    console.log(2);
});

firstTimeThreadResponse.subscribe(x => {
    console.log(1);
    threadStorage[x.clientInfo.clientId] = 'foo';
});
```
The output will be `2` and then `1` which is ok and it indicates that both subscriptions are working fine

With some experiments i've figured out that such effect will show if the source sequence has more than one `filter()` applied.
Also if the subscription has an interaction with the outside code (like in example above), the subscriptions which are defined after it, will never be fired

I also tried it with RxJS 5 - same thing.
Is this some kind of bug, or have i something misunderstood in the `subscribe` and `filter` mechanism?

<a class="jsbin-embed" href="http://jsbin.com/supalak/embed?js,console">Here is a JS Bin to see what i'm talking about</a><script src="http://static.jsbin.com/js/embed.min.js?3.35.11"></script>

**Comment by paulpdaniels** [comment]
You are having an issue because you are introducing side effects to your code. You are modifying the value of the object so it will no longer pass the second filter, and thus the second subscription is no longer triggered.

**Comment by rhendric** [comment]
Remember that with most Rx operators, each subscription at the end of a chain of operators creates an independent subscription at the beginning, and values from the source flow through the operators once for each subscription, not once overall. So both of your filters are evaluated twice, with different results the second time because the first subscription modifies the object.

If you want the filters to only run once for each value, add a [`.share()`](http://reactivex.io/documentation/operators/refcount.html) to the end of `firstTimeThreadResponse`. This creates a new observable that only subscribes once to the filters no matter how many times it itself is subscribed to.

**Comment by NXTaar** [comment]
@rhendric Thank you so much for your answer. I really thougth that subsciptions are recieving values at the same moment and that value goes through all opertors each time per subscription. I implemented '.share()'  in my case, and it works as i expected
