### ISSUE TITLE
Should Subject.share() return a Subject?

### ISSUE THREAD

**Issue by brian428** [Reactive-Extensions/RxJS#1215]
Building an Angular 2 app, and realized that calling share() on a Subject actually returns an Observable, not a Subject. To be clear, this isn't just a typecasting issue; that actual object returned from share() is an Observable, not a Subject. 

This seems counter-intuitive, and complicates things. I'm creating a subject because I want both Observer and Observable capabilities. Once I call share() on it, that goes out the window. So the only apparent solution if I want to share this is to drop the use of Subject and store separate references to an Observer and an Observable, then work with them independently. 

I don't see any obvious downside to having Subject.share() return a Subject. Anything using it that is typed to Observable will obviously be fine (since Subject extends Observable). And it would avoid needing to store separate Observable and Observer references just be able to share it.

Thoughts?

**Comment by paulpdaniels** [comment]
What is the point of sharing a `Subject`? Sharing is just preventing resubscription behavior with multiple subscribers which is a non-issue with a subject.

**Comment by brian428** [comment]
I'm certainly not an RxJS expert, but I thought that using share() would ensure that all subscribers always get the same values. In other words, share() makes it hot. 

Are you saying that Subjects are automatically hot, and that the issue with different subscribers getting potentially different results doesn't apply to Subject?

**Comment by paulpdaniels** [comment]
Yes `Subjects` are automatically hot. The `share` behavior is meant to share the underlying subscription to an Observable, which `Subject`s already do (in fact they are used internally in `share` anyway). 

Internally `share` is actually `publish().refCount()` the former of which produces a `ConnectableObservable`, which will internally use a `Subject`.

Naively you could think of publish as doing:

```javascript
Rx.Observable.prototype.publish = function() {
  var source = this;
  var subject = new Subject();
    
  //Here we define the behavior from source to subject
  var connectable = Rx.Observable.create((observer) => {
    return subject.subscribe(observer);
  });
  //When connect is invoked the subject starts receiving events
  connectable.connect = function () {
    //You can also dispose of the subscription to stop all down stream subscribers
    //from receiving events
    return source.subscribe(subject);
  };
  return connectable;
}
```

`refCount` additionally provides a first-subscribe-is-connect semantic, so that you don't have to have the out-of-flow call to `connect`.

More broadly this all falls under the `multicast` behavior of which you can use any of the flavors of `Subject` dependent on your needs (`ReplaySubject`, `BehaviorSubject`, `AsyncSubject`)
