### ISSUE TITLE
withLatestFrom does not work when Observable.create contains an asyncronous call to next

### ISSUE THREAD

**Issue by mildfuzz** [Reactive-Extensions/RxJS#1437]
(Test Case Here)[http://codepen.io/anon/pen/evVrya?editors=1010]

If we trigger an observable's next with an async request (in this case a setTimeout), the getLatestFrom has no value, even if we wait for the original async method to fire.

```
const test$ = Rx.Observable.create(obs => {
  setTimeout(() => {
    obs._next('hello world')
  }, 0)
})

setTimeout(() => {
     Rx.Observable.of(1)
        .withLatestFrom(test$)
        .map(([x, y]) => y)
        .subscribe({
            next: i => console.log(i)
        })
}, 1000)
```

**Comment by mildfuzz** [comment]
use `.combineLatest` instead

**Comment by whiteinge** [comment]
Glad you found a workaround. If you're interested, we added a custom operator for this use-case that we called [waitLatestFrom](https://gist.github.com/whiteinge/9dab34105233871f3d660d9b1056a7ad) because we didn't want the full semantics of combineLatest but we still had to deal with an async producer as that second argument.
