### ISSUE TITLE
Subject with bufferWithTime keeps firing

### ISSUE THREAD

**Issue by lmeyerov** [Reactive-Extensions/RxJS#175]
To reproduce, in JS console:

(new Rx.Subject()).bufferWithTime(100).subscribe(function (v) { console.log('hit', v); })

Expected result: No output.

Result: infinite stream of hit [], hit [], hit [], ...

This may be related to another bug where .sample() keeps running in the background even when it should be inactive. (In that case, subscribe won't be called, but CPU cycles will still activate, which prevents putting the app to sleep.)

**Comment by eschwartz** [comment]
This tripped me up too. I get your argument, but it was definitely not intuitive to me that the buffered stream would emit an event when no data is coming into the stream.

Maybe this could be documented in the `bufferWithTime` docs?

**Comment by alobakov** [comment]
I know this topic is old, but please add my vote for including this very useful operator into the framework. Just like the OP and the other folks, I was intuitively expecting with good certainty that the buffer would wait until there were values available, instead of producing an empty result every N milliseconds. Naturally, when we're thinking within the "Observable" (or reactive in general) realm, the typical expectation is that a subscriber will only be called once a value(s) becomes available on the observable, but not sooner. That is a **_reaction_**. 
The timeout parameter on the operator then looks like it merely defines a **_grouping timeframe_** within which **_any_** incoming values (if available) would be combined into one collection before calling subscribers, provided there's something to produce.
Reason for this thinking being : if not for this expectation, then why bother using an observable at all for this case? One could easily accomplish the same buffering behavior with a simple timer and a plain buffer array, which doesn't sound reactive at all as it produces dummy loops and wastes CPU cycles.

**Comment by daniel1943** [comment]
Any news on this?

**Comment by Restuta** [comment]
Same here, was not sure why it behaves like that, then read this thread and I agree having "lazy" buffer would be nice. I tried to port above code to Rx5 without luck yet. @mattpodwysocki do you have any guidance on how to contribute? Would you consider a PR that adds that operator?
