### ISSUE TITLE
Proper way to get latest value of several BehaviorSubjects

### ISSUE THREAD

**Issue by sgerace** [Reactive-Extensions/RxJS#177]
I'm using a `BehaviorSubject` to bind username and password fields to the underlying state in a login page and I'm wondering the correct way to retrieve this state at a single instance (for example, when the user clicks the login button). At the moment, I have something like this:

``` javascript
var username = new Rx.BehaviorSubject('username');
var password = new Rx.BehaviorSubject('password');
// Bind these subjects to DOM, e.g., using RxJS-jQuery
btn.onClick(function () { // On click handler for button
  username.combineLatest(password, function(uname, pword) {
    return {
      username: uname,
      password: pword
    };
  }).subscribe(function (creds) {
    // Perform ajax queries using creds.username and creds.password
  });
});
```

Which seems to work, but I'm wondering if (a) there is a better/simpler way to accomplish this task and (b) if I should be disposing of this subscription somewhere (perhaps immediately inside the `onNext` handler since I have obtained the latest version of the username and password at the point the button was clicked).

**Comment by GDoronin** [comment]
Hello, @mattpodwysocki you said
> there is always a constant `value` property that you can obtain

I wonder if it is supposed way of getting the value from the `BehaviorSubject`? Doesn't it contradict asynchronous nature of Rx?
It looks pretty clean and straightforward for me however..

But also found some confusions (listing below).

1. There is no such a property in documentation
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md

2. In .NET version too
https://msdn.microsoft.com/en-us/library/hh211949%28v=vs.103%29.aspx

3. However here I also noticed the answer about using `Value` property
http://stackoverflow.com/questions/21961508/behaviorsubject-first-obsolete-what-is-the-alternative

4. Here, Marcus said about using .First(), and then mentioned about `blocking code`, which confused me even more, because `Value` isn't asynchronous at all.
https://social.msdn.microsoft.com/Forums/en-US/d2c2cce2-c2f8-4b63-ae96-11f9230f42ad/how-can-i-get-the-last-value-of-a-behaviorsubject-asyncsubject-synchronously-?forum=rx

Thanks in advance for your answer.

**Comment by GDoronin** [comment]
I'm still thinking about it..

Let me make more exact my last words about
> contradict nature of Rx

It still seems for me that `value` is supposed to be private thing, and its purpose is only to store the last value of `BehaviorSubject`, not to obtain this value from external code.

So `value` shouldn't be exposed to public scope.
Yes or no? @mattpodwysocki 

I understand it doesn't matter for javascript, but it does for typescript however.

**Comment by mattpodwysocki** [comment]
@GDoronin the `value` property is indeed public just as it is in .NET's `BehaviorSubject`.  It's perfectly fine to obtain the value from it.  Remember, RxJS is not asynchronous by default, in fact, it's perfectly synchronous unless you add a notion of time, but then it's no longer a BehaviorSubject.

**Comment by mattpodwysocki** [comment]
@GDoronin if it's not in the documentation, then that's a bug.  Feel free to file an issue on that to get it fixed.
