### ISSUE TITLE
Switch Subject? 

### ISSUE THREAD

**Issue by blesh** [Reactive-Extensions/RxJS#455]
I have need to be able to switch to the latest subject in an Observable of Subjects.

Basically I have an observable of incoming WebSocket subjects, and I need to switch to the latest one of them cleanly.

**Comment by urmastalimaa** [comment]
> I have need to be able to switch to the latest subject in an Observable of Subjects.
>
>Basically I have an observable of incoming WebSocket subjects, and I need to switch to the latest one of them cleanly.

Why are the WebSockets `Subjects`?
If they were `Observables` then `flatMapLatest` might be a perfect fit.

`Subjects` are mostly used internally in `Observable` _operators_ and to provide a thin interoperability layer between existing imperative code and `Observables`.
They are not commonly used because they encourage imperative shortcuts. With `Subject` `onNext`, `onCompleted`, and `onError` calls might be all over the codebase, `Observable` forces you to have it at the definition.

I'd be happy to help you redesign your code to remove `Subjects` completely or encapsulate them.

**Comment by blesh** [comment]
@urmastalimaa - WebSockets are Subjects because they both accept input and emit events from one underlying object. You want your socket to be wrapped in an observable, so messages arriving can be emitted, *and* so it doesn't connect until the observable is subscribed to (or published and connected), and to send to the socket in an Rx-conformant way you want to have the socket wrapped in an observer where `onNext` can map to `socket.send`. So since you want your *one* socket to be both an observable *and* an observer, a Subject is the perfect fit. Otherwise, how are you going to create a separate observable and observer that both use the same socket, but not have the socket connect until the observable is subscribed to? They need to be part of the same construct.

**Comment by blesh** [comment]
@urmastalimaa  - FWIW, I originally thought the exact same thing you did.

**Comment by urmastalimaa** [comment]
I see where you are coming from. 

I have tackled the problem by splitting my input and output and doing the plumbing from and to _websockets_ on the top level.

Adding `switchSubject` to `Observable.prototype` would not really make sense.
The basic problem is that all the current operators on `Observable` produce an `Observable` allowing combinations of them.
An operator which produces a `Subject` would break out of the `Observable` monad and would not fit in.

You could add an operator to `Subject`, but such operators are unprecedented at the moment (_switch_ might be one the few operators which actually makes sense in the context of a `Subject`). 
Not really sure about this because propagating `onComplete/onError` from the users of such operator to the underlying `Subjects` in a way consistent with the `Observable` contract might be really akward.

**Comment by blesh** [comment]
Ah... but Subjects *are* observables. ... they're just also observers. WHAT NOW, @urmastalimaa ?! (I kid, I kid)

... this is exactly why this Issue is more of a question. "Does it belong?" I have no strong opinions.
