### ISSUE TITLE
`flatMap` and `merge` are not lazy

### ISSUE THREAD

**Issue by valeriangalliat** [Reactive-Extensions/RxJS#503]
I'm not sure it's a bug, or expected behavior, but I just realized that `flatMap` and `merge` will consume the whole stream even if we `take` part of it after (and that's a problem for me because I'm sometimes working with infinite streams).

Here's an example:

```js
Rx.Observable.range(0, 3)
  .map(function (x) {
    console.log('called', x);
    return Rx.Observable.just(x).delay(1000);
  })
  .merge(1)
  .forEach(console.log);

// Will display `called {0,3}` immediately, then display `0 1 2` with 1s delay between each.
```

```js
Rx.Observable.range(0, 3)
  .flatMap(function (x) {
    console.log('called', x);
    return Rx.Observable.just(x).delay(1000);
  })
  .take(1)
  .forEach(console.log);

// Will display `called {0,3}`, then display just `0`.
```

Am I missing something? How can I have a similar flow without consuming the whole original stream first?

Typically I'm using the following function and than use `take*` functions on it (related to #499):

```js
function infiniteRange(start, increment) {
  return Rx.Observable
    .range(start, Number.MAX_VALUE)
    .map(function (x) { return x * increment; });
}
```

In this very case I really don't want the "infinite" observable to be entirely consumed if I take only a small subset of it.

**Comment by valeriangalliat** [comment]
I got it working by replacing `Rx.Observable.range(0, 3)` with `Rx.Observable.interval(0)`, and with the following `infiniteRange` implementation:

```js
function infiniteRange(start, increment) {
  return Rx.Observable.interval(0)
    .map(function (x) { return start + (x * increment); });
}
```

So I consider this issue is solved, though I really don't get why `merge` and `flatMap` will iterate through the whole input when it's a `Rx.observable.range`, and I'd **really** appreciate some clarification on this.

Thanks!

**Comment by valeriangalliat** [comment]
I closed too fast… while it seemed to work with my previous "fix", it's still (this time asynchronously) trying to consume the whole infinite range during the program execution.

Here's an example:

```js
var Rx = require('rx');

infiniteRange(0, 1)
  .map(function (x) {
    console.log('called', x);
    return Rx.Observable.just(x).delay(1000);
  })
  .merge(1)
  .take(5)
  .forEach(console.log);
```

Without the `console.log('called', x)`, it looks like it works fine (and lazyly since the program exits when the 5 items are processed), but with the log we can see it's consuming the infinite range in background during the whole program execution.

I also tried using an ES6 generator function but I have the same problem as initially with `Rx.Observable.range`.

So I switched to Highlands.js, and here's the working equivalent:

```js
var _ = require('highland');

function infiniteRange(start, increment) {
  return _(function (push, next) {
    push(undefined, start);
    start += increment;
    next();
  });
}

infiniteRange(0, 1)
  .map(function (x) {
    console.log('called', x);

    return _(function (push, next) {
      setTimeout(function () {
        push(undefined, x);
        push(undefined, _.nil);
      }, 1000);
    });
  })
  .parallel(1)
  .take(5)
  .each(console.log);
```

Here the infinite range will be consumed lazily, that is, only 5 values will be taken from it.

Isn't it possible to do the same thing with RxJS? I tried everything I could with RxJS but I can't get it to work. :cry:

**Comment by trxcllnt** [comment]
@valeriangalliat This is because Rx is push-based; the Observable controls when the consumer receives values.

In your first example, `range(0,3)` [synchronously] pushes each of its values to `flatMap`, which selects them into delayed values. The `take(1)` is notified of an event when the first delayed Observable onNexts, which is after the range has finished onNexting to `flatMap`.

Swapping `range(0, 3)` for `interval(0).take(3)` changes how the source (the range or interval) onNexts to `flatMap` (range uses the `currentThreadScheduler`, interval uses the `timeoutScheduler`; you could accomplish the same thing by specifying `range(0, 3, Rx.Scheduler.timeout)`), but the effect is the same: `take` only hears about the events coming from `flatMap`, by which time it's too late to unsubscribe from the `range` or `interval`.

If you don't want your delayed values subscribed to in parallel, you can use `concatMap` instead, which will subscribe to each inner source sequentially.

If you need to switch some parts to a pull-based model, Rx's sister library Ix gives you Enumerables, similar to ES6 Iterators. The Rx and Ix APIs are very close, though Ix has lagged behind a bit because @mattpodwysocki is so busy on everything Rx.

Hope this helps!

**Comment by valeriangalliat** [comment]
Wow thank you very much @trxcllnt for this explanation!

I'll give a try to IxJS (I wasn't aware of this library, there is no mention about it in Rx docs!), I'm indeed searching for a ES6 iterators-like behavior.
