### ISSUE TITLE
repeat hot observable causes stackoverflow

### ISSUE THREAD

**Issue by wilfrem** [Reactive-Extensions/RxJS#515]
Repeat hot observable which was already completed causes 'Maximum call stack size exceeded' error.

```typescript
Rx.Observable.of(1).share()
        .repeat()
        .subscribe((i: number) => console.log("onnext: " + i));
```

(I know repeat operator doesn't make sence in this code, repeat completed only.)

**Comment by mattpodwysocki** [comment]
@wilfrem what are you trying to do here?  Yes, realizing it causes problems here and investigating

**Comment by wilfrem** [comment]
Thank you for your reply.

I found such code in co-workers' code. (he was rx beginner at that time)
He was trying to manipulate countdown message stream that started by click event (hot observable), pause and rewind some status changed by using takeUntil, repeat and some operators.

That code I wrote is simplified. The actual code is complex.

So, We think two things.

1. Is there anything relief for beginner who fall into a pit in such case?
2. Stack overflow looks like an bug, even though wrong use of repeat operator.

**Comment by mattpodwysocki** [comment]
@wilfrem I fixed the stack overflow issue already by switching the immediate scheduler usage to the current thread usage which has a trampoline to avoid it.  The problem is now that it completely eats up the CPU as you're doing the wrong thing.  The problem with `share` here is that you're continuously creating new `refCounts` or rather incrementing the ref count counter which is obviously bad so that it spins out of control and never actually exits.

**Comment by wilfrem** [comment]
Thank you. I share this.
