### ISSUE TITLE
shouldn't toPromise() reject the promise if the observable completes with no value?

### ISSUE THREAD

**Issue by bman654** [Reactive-Extensions/RxJS#538]
It should reject with something like `new Error('sequence contains no elements')`.

This would give parity with the c# `ToTask` and `GetAwaiter` IObservable extension methods and would prevent "deadlocks" if someone [awaits](https://github.com/Microsoft/TypeScript/issues/1664) an empty observable.

**Comment by mattpodwysocki** [comment]
@bman654 I'd rather err on the side of sending undefined than throwing an error.  There may be sequences that are empty and that's ok, as long as it didn't throw an error.  Would it be any different than `onNext(undefined)`?

cc @domenic

**Comment by domenic** [comment]
My take on this is that if an observable completes, instead of errors, it seems strange to signal that with a rejected promise.

If the method was named `promiseForFirstElement()` instead of `toPromise()` I could understand rejecting. But as-is it's already a pretty lossy, heuristic conversion.

That said, @bman654 sounds like an actual customer of this library, whereas I'm just theorycrafting. So his arguments should probably hold more weight. The C# analogy is perhaps a good point.

**Comment by bman654** [comment]
You feel strong enough to have different behavior (and resulting developer confusion) vs .NET?  Note one can always avoid the error if they think an empty result is possible by using something like `.defaultIfEmpty()`, not to mention if it manufactures an `undefined` it makes it difficult to tell if the observable *produced* `undefined` or if it was empty...

I was going to say it isn't conceptually any different than `first` which throws if empty.  But I just checked and indeed the RxJs implementation does not throw (the c# version does).  Note this also deviates from Ix's `Enumerable.first`, which does [throw](https://github.com/Reactive-Extensions/IxJS/blob/34db3993678f9e04bd0712a313c97f701e5ddc9c/src/core/enumerable.js#L399) if empty.

So you have some precedent to match your `first` behavior but it feels pretty dirty to not match the c# behavior without good reason.  And feels very dirty to have different behavior between Ix and Rx.

All I know for now, is having it silently do nothing is pretty bad.

**Comment by mattpodwysocki** [comment]
@bman654 that's not true at all, `first` does indeed throw which is proven by [this test without a predicate](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/first.js#L10-L26) and [this test with a predicate](https://github.com/Reactive-Extensions/RxJS/blob/master/tests/observable/first.js#L105-L126)

I'm fine with throwing an Error if there is no resolution, but that's a breaking change.

**Comment by bman654** [comment]
@mattpodwysocki My mistake.

Technically a change either way is a breaking change?

**Comment by mattpodwysocki** [comment]
@bman654 correct.  I'd rather err on the side of being correct.  If consensus is that the best idea is to keep with the semantics of C#, I have no problem doing so, but I'd like some consensus from the larger JS and Rx community

**Comment by benjamingr** [comment]
I'm just throwing ideas out here (haven't thought enough about it yet) but wouldn't it make more sense if `toPromise` returned an array of values rather than a singular value (for the last one).

That way you get:
 - `[]` the observable completed successfully but yielded no values
 - `[x]` the observable completed successfully and yielded one value
 - `[a,b,c,d,...]` - the observable completed successfully and yielded several values.

It sounds to me like it'd make the method more useful too - for example if I have an observable for the contents of a file I now get all the file's chunks in the promise when the download/read completes and so on. 

I think the "real world" parallel of `toPromise` is the common node callback pattern of doing:

```js
var data = []; // or buffer, or another aggregator
emitter.on("data", function(chunk){
    data.push(chunk); // or otherwise aggregate
});
emitter.on("end", function(){
    callback(data);
});
```

**Comment by paulpdaniels** [comment]
@benjamingr while in general I like the idea, it may start to stray from user expectations, I think that it should tend to be a drop in replacement for where users are currently using promises.  It would mean additional refactoring work if we said Promise<T> now returns T[].  The behavior you specified could just as easily and more declaratively be done with aggregate().

@mattpodwysocki I am coming down on the "empty promises should reject"-side, both for the consistency reasons presented by @bman654, and because I think it is the only way make up for the loss of clarity converting Rx to Promises (that being, there is no way to distinguish between a produced _undefined_ and an empty observable whereas a rejection can be parsed for a reason and subsequently ignored if needed).

**Comment by benjamingr** [comment]
> @benjamingr while in general I like the idea, it may start to stray from user expectations, I think that it should tend to be a drop in replacement for where users are currently using promises. 

Right, and conceptually an observable represents multiple values rather than just one (the last one) so the correct way to model it would be a promise for an array where the promise resolves when the array is ready. You could then do:

    myObservable.toPromise().then(x => x[0]); // if you want the first value the observable yielded
    myObservable.toPromise().then(x => x[x.length - 1]); // last value

You get the idea :) 

This way an empty sequence is not an edge case at all but similarly just another case - I definitely think this is a more robust implementation since it models the domain better. A promise from an observable is always a promise of `T[]`

As for a single value, I can see why you'd want that sometime but if the default is a promise for the collection having something like a C# `First` (and Last etC) that throws on sequence has no elements makes sense.

> It would mean additional refactoring work if we said Promise now returns T[]. The behavior you specified could just as easily and more declaratively be done with aggregate().

I don't think it could, aggregate doesn't return a promise last time I checked :) But in seriousness yeah, aggregate inherently does something very similar (it's not a surprise either given what the conversion between an observable and a promise represent).

**Comment by bman654** [comment]
The downside to making `toPromise()` resolve to an array of values is that it makes working with singleton observables a pain in the rear.

**Comment by paulpdaniels** [comment]
@benjamingr to clarify my previous statement I meant that one could use aggregate with toPromise to achieve the same effect (though I just remembered toArray also exists)
Like so:
```javascript
sequence.toArray().toPromise();
```

**Comment by benjamingr** [comment]
@bman654 only when using native ES6 promises _and_ are not using ES6 desturcturing.

With ES6 destructuring:

    sequence.toPromise(([el]) => ... ); // unwrapped array in parameter

With some promise libraries like Q and bluebird:

    sequence.toPromise().get(0).then(... // gets the first element for example

You would in both these cases get a rejection if the array contains no elements.

I agree that an array might be less in terms of syntax in some cases but it is much much more correct IMO.

**Comment by Igorbek** [comment]
I'm completely for returning last value only and throwing when sequence is empty.

1. promises have same semantics as .Net Tasks;
2. `Observable.ToTask` captures only last value and produce `OnError` if observable is empty;
3. awaiting of observable has same behavior as awaiting `Task` converted from observable;
4. `ToTask` as well as RxJS's `toPromise` is used for single values only in most cases, so it shouldn't breake a code significantly;
5. returning some default value (`undefined`, why not `null`?) is terrible practice; there's no way to distinguish it from produced one; furthermore, it's done implicitly.

**Comment by blesh** [comment]
I still wonder what real-world scenarios come up where someone wants to convert an Observable to a Promise. It might give better insight into what the developer might be expecting.

But as an aside, the whole thing baffles me. Promises and Observables, in theory, have similar allocation costs, but Observables are much more versatile. It's like saying, "I have this swiss army knife for $20, but I think I'd like to trade it for this $20 butter knife". I can't think of many scenarios for this.

**Comment by benjamingr** [comment]
@blesh that's like saying arrays are more versatile than regular objects or primitives since you can 'filter' them etc.

Using observables for singular values is exactly like using arrays for all your variables. When all you have is a hammer every problem starts to look like a nail.

**Comment by benjamingr** [comment]
In your analogy - it's like using your Swiss army knife to cut butter when you have also have a butter knife out. Promises and Observables complement each other - they're certainly not mutually exclusive.

**Comment by blesh** [comment]
In my analogy, the swiss army knife also had a butter knife built in.

```js
promise.then(something).then(something).then(success, error)
```

vs

```js
observable.map(something).map(something).forEach(success, error);
```

1. If your promise fails and you don't have access to the method that created it, you can't retry it. 
2. The promise is only good for one event.
3. Promises can only schedule with implicit scheduling in their handlers (there's no `observeOn`)

The *only* thing I like about promises over observables is that A+ compliant promises are guaranteed to always be asynchronous, where Observables are *sometimes* async and sometimes not, which can be very confusing for developers.

So... yeah. It's a weird thing that people want a promise.

Maybe they're using some third party API that expects a Promise?

**Comment by benjamingr** [comment]
In my analogy, an array can also contain a single value.

```js
myArray.map(fn1).map(fn2).map(fn3).forEach(handler);
```

vs

```js
     x = fn1(x);
     x = fn2(x);
     x = fn3(x);
     handler(x);
```

1. While a value can only represent a single value an array can present multiple values (also, it can still represent a single value so it has that ability built in).
2. Arrays can filter values and can do clever manipulations when they map or reduce them. Values can only in function calls etc.
3. Arrays are everywhere, have better stack traces so there is literally no reason to ever use anything except arrays for manipulation. Why write `fn(1,2)` when you can `[1,2].reduce(fn)`? Just do the same thing every time - much stronger abstraction than singular values - scales better.

--------------------------

Now in all seriousness an asynchronous value (a promise) and an asynchronous iterable (an observable) simply do different things. In a decent promise implementation like (bluebird) you can do the stuff you complained about above `Promise.setScheduler`. The fact it's "good for one event" is a part of what the abstraction is - just like not everything is an iterable.

I suggest you watch some of Erik Meijer's talks or read KrisKowal's [gtor](https://github.com/kriskowal/gtor). I don't want to derail this discussion about `.toPromise` on why "an abstraction of everything" is an inherently problematic concept and why observables and promises complement each other any further. You can send me an email at benji at tipranks dot com if you're genuinely interested.

**Comment by blesh** [comment]
> @blesh that's like saying arrays are more versatile than regular objects or primitives since you can 'filter' them etc.

Primitives, Objects and Arrays are allocated in different ways (they have different "costs"). And they're all designed for different purposes.

Promises and Observables are allocated in similar ways (they have a similar "cost"). And they're designed for the same purpose: Dealing with asynchronicity.

| |Promise|Observable|
|:--:|:--:|:--:|
|async|X|X|
|chaining|X|X|
|catch|X|X|
|finally|X|X|
|merge|X|X|
|retry| |X|
|repeat| |X|
|single event|X|X|
|multiple events||X|
|zero events||X|
|scheduling||X|

It's a strong opinion, weakly held, as I *used* to be in the camp of "Promises and Observables complement each other". Which they can, I suppose. But @jhusain convinced me that Observables are really a better pattern than Promises. 

I like promises. I don't *dislike* promises. I just can't figure out why I'd want a promise if I have an observable. What am I gaining?

**Comment by blesh** [comment]
It's not really "values" vs "Arrays"... an integer is allocated in memory in a completely different way than an Array.  Promises and Observables, however, have a similar cost.

**Comment by blesh** [comment]
To be clear: I'm not saying Promises are "wrong". I'm just trying to understand the use case for conversion to a Promise.

**Comment by Igorbek** [comment]
@blesh @benjamingr it's seems like offtopic =)
Let's back to primary discussion.
Once again, `Promise` is a direct analog of `Task` in JS world. I sure `toPromise` should be consistent with `ToTask`.

**Comment by blesh** [comment]
@Igorbek Most of my career was spent in .NET development. That said, I don't think it's a good idea to gauge JavaScript developers' expectations by what .NET would do. If the operator were called 'toTask', then I'd be more inclined to agree.

JavaScript developers can't be expected to know the behavior of a .NET library, or that Tasks are similar to Promises. I wouldn't say they are "analogs", To be analogs they'd need exactly the same API at the very least. They're similar in that they are both read-only views of a future.

**Comment by Igorbek** [comment]
ok, anyways, main point is the fact that promise represents a single value always (or failure).
The conversion between empty sequence to some "default value" which is `undefined` is implicit and there's no way to distinguish it from fairly produced `undefined` value. And these two cases have completely different meaning.

I could agree to introduce `toPromiseOrDefault(default?)` operator to allow producing default value if sequence is empty.
It's a responsibility of developer to make sequence non-empty before calling of `toPromise`. He could make it by `defaultIfEmpty` or `toArray`, etc. But don't produce indistinguishable values, please.

**Comment by blesh** [comment]
So I had a main point to this above which you dismissed as "off topic". But that point is that Promises are simply inadequate in a variety of ways. This is one of them. 

Observables: 0 - N events + completed
Promise: 1 event

Clearly this isn't a situation were you create a Promise that suits every observable.

A completed observable is not an "errored" observable, therefor it should fall into the Promise's success pathway. If that means that the developer who choose to convert an empty Observable to a Promise gets an undefined, then I'd say it sounds about right. I can't think of a logical reason to use `toPromise` anyway, other than to accommodate some third party API that expects a promise.

**Comment by spion** [comment]
@blesh where Observables are inadequate when you want to re-use the value. If you store a promise inside a variable, you can reuse its value many times by attaching a handler (just like you would reuse a value in a variable normally)

**Comment by benjamingr** [comment]
@blesh like I said - enumerating `0-N` values where completion is ending it and errors are errors is simply mapping an `Observable<T>` to a `Promise<T[]>` conceptually. There is nothing hard in expressing that and it's quite obvious from what the abstractions actually represent.

As for the promise vs. observable argument - the fact something can "do more" than something else doesn't make it the right choice just like `dynamic`` can express more things than a class type `T` in C# but you wouldn't use it for everything would you? I can only suggest again that you read [gtor](https://github.com/kriskowal/gtor). Just because something can represent more things doesn't make it a better representation.

**Comment by trxcllnt** [comment]
@spion nah dog, [publishValue](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/publishvalue.md)'s got your back there.

**Comment by spion** [comment]
@trxcllnt so to get the same behavior as promises, for this example function:

```js
function getUser(name) {
  return db.connect().then(conn => conn.query(getUserQuery, name));
}

var u = getUser(1);
var friends = u.then(u => getFriends(u.id));
var enemies = u.then(u => getEnemies(u.id));
```

what exactly would I need to do?

**Comment by trxcllnt** [comment]
@spion 
```javascript
function identity(x) { return x };
function getUser(name) {
  return db.connect().flatMap(conn => conn.query(getUserQuery, name))
}
var user = getUser(1).publishValue().refCount().filter(identity); // filter out falsey values
var friends = user.flatMap(u => getFriends(u.id));
var enemies = user.flatMap(u => getEnemies(u.id));
```

Multicasts a single subscription to `getUser` through a BehaviorSubject so the `friends` and `enemies` subscriptions don't cause multiple `getUser` queries. If you need multiple subscriptions to either `friends` or `enemies` Observables without re-invoking their queries, you can publish them too.

**Comment by benjamingr** [comment]
(As a general note you can filter falsey values with `.filter(Boolean)`)

**Comment by trxcllnt** [comment]
@benjamingr 👍 gr8 tip thx

**Comment by spion** [comment]
So this will work if I want to save the user for later consumption? What if I want to chain another action much later, after some other unrelated process completes?

**Comment by blesh** [comment]
It's not that it simply "does more", it's cost versus benefit. Same cost, more benefit.

**Comment by trxcllnt** [comment]
@spion Yes, this was designed for that case. `publishValue` is literally just multicast with a BehaviorSubject, take a look at [BehaviorSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md) for more info.

**Comment by trxcllnt** [comment]
@benjamingr the point about scalars vs. vectors @blesh brought up is entirely valid -- we have to allocate a callback on the heap regardless of whether we receive one value or multiple, so there's no cost savings in going with a scalar-only abstraction. Furthermore, building the multi-value Observable on top of Promises is incredibly inefficient (as @jhusain and I know from building the ES7 Observable POC).

**Comment by benjamingr** [comment]
You guys keep bringing up performance overhead.. but let's ignore performance (ftr bluebird is much much much faster than RxJS - by a factor of ~10).

It's not about the overhead of allocating a scalar vs an array, it's about correctness of abstraction. The reason we don't write `[x]` everywhere isn't because allocating an array is expensive - it's because representing a singular value with a value contained in an array is less representative of our problem domain. 

Just like the point @spion is trying to make - when your method gets a promise you _know_ it will never change value - I'm not arguing an observable can't simulate this behavior but from the consumer side it's not guaranteed.

An observable abstracts a sequence - a promise abstracts a value. Just because a value is a special case of a sequence with length 1 doesn't mean that I want a sequence of length 1 every time I'm expecting a value. I'm really not sure why you think it is. Promises and observables are at odds just like values and arrays are at odds - they're not. They're different concepts that complement each other.

Again, I really recommend reading Kris Kowal's GTOR or at least watching some of Erik Meijer's lectures - Meijer is realy smart and a lot better at explaining the difference between a future and an observable than me - there's also the added bonus that he wrote the abstraction which is the base of this one :D

**Comment by trxcllnt** [comment]
@benjamingr I'm not sure who you think you're talking to -- beyond just watching Erik's presentations, a few of us here have actually worked with the man.

I can't argue against whether you believe a scalar type more correctly models a certain problem domain or not -- many engineers (including myself) have no problem reconciling a solution expressed as a series of monadic transformations on single-value vectors. The reason we use single-value vectors instead of scalars is because when requirements change, the vector is simply more future-proof.

Yes, scalar types only exist because the overhead of allocating containers for every scalar was prohibitively expensive forty years ago (and aside from reliance on recursion, this is the other reason LISP wasn't practical on Von Neumann architectures). Going async, we have no choice but to allocate the callback, so there's no longer any concrete benefit to a scalar type.

Please also don't confuse my argument for Observable's theoretical performance characteristics as a defense of Rx's performance characteristics. Rx can and will get better (examples like Rx 2.0, [most](https://github.com/cujojs/most) and my own fork of [RxJSx](https://github.com/trxcllnt/rxjsx) prove that there's room to improve). But the point stands that creating a wrapper Promise for each value in an asynchronous vector is flat-out backwards.

Promise is a subset of the Observable calculus, not a separately useful abstraction. You want an instance that represents a past-or-future scalar value? Use an [AsyncSubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/asyncsubject.md). Then you can get back to solving the 90% of other problems that require vectors, because your tools were designed to help you solve more than just one type of problem.

**Comment by benjamingr** [comment]
The fact you've worked with the man is why I'm finding this frustrating - you're supposed to know all this :D

Just because something can represent more values doesn't make it better. A great way to 'future proof' your APIs in C# for example is to use `dynamic` for everything - very future proof - will be able to use any type in the future.

Scalar types do not only exist because of allocating containers is expensive - scalar types exist because sometimes what you want to represent is a scalar. A number is a number, it's not an iterable with a single value that returns a number. A string is a string - it's not an iterable with a single value that returns a string.

Also - from what I understand no one suggested creating a promise for every value for an observable (although that's an interesting approach for pull streams which are not the topics here) - rather, the suggestion is making a _single_ promise for the whole stream. 

Just because something is a subset of something else doesn't mean it's not a useful abstraction. That's like saying booleans are useless because boolean calculus is a subset of real calculus, or that real numbers are useless because real number calculus is a subset of complex calculus - sometimes all you have is a boolean and you really just want to represent that by returning a boolean and not a general abstraction on the concept of zero or more values possibly over time.

Having tools that solve one type of problem is immensely useful for the consumer of the API - if someone calls a method that returns a promise they have a much narrower (as you say, a subset) return type which is absolutely fantastic.

**Comment by trxcllnt** [comment]
@benjamingr I want to apologize for the tone of my last post, it was unnecessarily aggressive, and I certainly don't mean to argue via an appeal to authority. 

I suppose here we'll have to agree to disagree. I'm familiar with everything you've argued for, but I've never found more value in expressing an API as Promises instead of Observables. Being a library author, I understand the benefits of restricting certain classes of operations for the sake of expressiveness (or other features, like determinism or caching), but I haven't found a case where using a single-value Observable was even slightly more complex than using a Promise, but I know of many cases where the opposite is true.

**Comment by benjamingr** [comment]
@trxcllnt to be fair my tone here is very argumentative and unnecessarily aggressive too (apologies :D). I love Rx and RxJS and use it in projects - I find observables a very useful abstraction for things they model. I'm all for eventually making them native - I just think they model different things.

There are _tons_ of cases where promises would downright _not work_ when modelling problem that represent more than one value - I've answered at least 10 questions in SO with "don't use promises for this" when asked how to model an event stream like problem with promises. I think everyone here understands why the abstraction is important.

I think the reason promises are used for certain operations is simply because they make more sense there - a promise is a single eventual value. Imagine `yield`ing observables - you just want to wait for one value, it doesn't make much sense to `yield` a sequence - now a `for... on` (assuming that's the proposal you worked on) on the other hand is an awesome way to do that.

Yes, you can model a lot less problems with promises and their behaviour is a lot more fixated and that's a very very nice thing sometimes (rom a library author perspective, and generally when you want to reason about APIs you wrote before. Looking at your graph above you _know_ that it's a singular cached _value_ with no operation logic, that its state is immutable and so on. It's easier to reason about what it does (it doesn't start or end, no interim steps, it just resolves once, no retry logic, no zero events, no multiple events) - I argue that all these things are pros for problems that model that. Every time you constraint your argument or return values you're limiting future-proofness in some way but you're also introducing a contract and that's very important.

Now example you're writing a library that reads a `.someformat` file, parses it and returns all its rows. It is usually beneficial to look at this as a streaming problem observables model well but it's entirely possible someone might want to read the whole file at once and get the result (in order to close the observable triggering disposing logic earlier for instance) - it's entirely possible to do this using an observable as mentioned above but as someone reading the library API docs that method returning a promise makes much more sense as a consumer.

Having `.toPromise` do just that makes sense - just take the items you would normally map over, aggregate them to an array and return a promise for that array (returning a promise for a more generic iterable is also ok, but that implies some form of laziness which isn't really valid here so I like arrays better for this).

**Comment by trxcllnt** [comment]
@benjamingr But that's something you can express in a type system, or comments (or both)! An API with container types that don't interop seems hellish, especially if one is entirely obviated by a feature from the other. Multicasting your Observable through an AsyncSubject instead of returning a Promise maintains compositional semantics, which just makes everyone more efficient.

I understand the desire to explicitly denote a single value by choice of container type, but that's an implementation detail better specified by the consumer. I recognize that's an opinion, so I'll confine this to the realm of style discussion and agree to disagree.

Ultimately, I'm frustrated by and don't understand why the community seems so hell-bent on inventing half-baked solutions to thoroughly solved problems.

**Comment by benjamingr** [comment]
Basically because promises can be criticized on many levels but they're not
a 'half baked' solution - they are a technique developed over the course of
tens of years by some really smart people. It's not a half baked solution
by any measure but it's a tried and tested approach since the 80s and it's
implemented in virtually every mainstream language that needs to deal with
asynchronous calculations as a language feature (Java, C#, C++, Python,
Scala, etc) and lots of non mainstream ones (like clojure, CL, Dart etc).
It's a lot easier to reason about than an observable and it's a lot simple
than an observable. It doesn't invert control nearly as much as observables
do. Like you said this is a consequence of it being a tool for a specific
concurrency problem and not for many problems.

Even if you had a type system - you'd still need to return the different
container. It's not any more 'by container type' than a nullable container
denoting information about the value by type.

Promises interop just fine - as you probably know RxJS will gladly
assimilate a promise and once toPromise here is settled interop will work
on the other side too. This interop is what we're here to fix in this issue
though :)

**Comment by blesh** [comment]
@benjamingr ... if it's any consolation I fought this battle (if it can be called that) from your side once. I've been convinced otherwise. Heh. I've sat in meetings at Google and Netflix and witnessed this same conversation a dozen times fought by people *WAY* smarter than I. 

All I want is to plant the seed of an idea that Promises should be reconsidered as the go-to for modern async APIs in JS. Just a seed.

And I'll be 1000% happy to find out I'm wrong, or that there's an even better pattern somewhere. Because then I'm learning something. Which is the fun part, after all.

Fantastic discussion, all. (even if we broke the topic, haha).

**Comment by Igorbek** [comment]
So, maybe quick voting of "shouldn't toPromise() reject the promise if the observable completes with no value?" =)
My is vote for: _rejected promise for empty/error observable, and fulfilled promise with last value for others_.

**Comment by blesh** [comment]
My vote is an empty observable isn't in error, so not an error on the promise.

Observable.empty().toPromise().then(console.log); // undefined
Observable.throw('blah').toPromise().then(console.log, console.error); //Error: blah

**Comment by benjamingr** [comment]
@blesh I guess my main resentment is from the idea that there is a "go to" mechanism for modern async APIs in JS. Writing and modeling async APIs is a huge issues - there are cases where promises model an operation concisely and well and there are cases an observable models the problem much better - there are of course cases where neither model the problem well. 

I'm not saying you're "wrong", I'm saying that the whole notion of saying that there is a silver bullet to the huge issue of writing async code is itself problematic. I think it's super important to have a whole toolbox of constructs to deal with different asynchronous tasks rather than just a hammer :) 

@Igorbek I vote for "It should not reject the promise" since in JavaScript unlike C# accessing an array element at an out of bound index returns undefined and unless you're interested in returning an array for hte promise that's the least surprising thing that can happen IMO.

**Comment by spion** [comment]
Regarding interoperability, [Dart's API already has the answer - (don't they always)](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.Future#id_asStream). Promises just need to be convertable to observables, and observables just need to be convertable to promises. There should be a standardized minimal interop API for observables (like Promises/A+) and then promise libs can rely on that.

I imagine an interop API for observables would benefit observable libs as much as A+ benefited promise libs.

**Comment by mattpodwysocki** [comment]
All: I'm leaning towards just keeping it as is.  If an Observable is empty or never has a value, eg `Observable.empty()` and `Observable.never()`, then it shouldn't resolve the `Promise` either.
