### ISSUE TITLE
Try to optimize try/catch/finally

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#586]
Some [performance issues in v8](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers) can arise due to try/catch/finally and cannot be optimized.  Some areas to note are:
- [`AutoDetachObserver`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/autodetachobserver.js)
- [`Scheduler.currentThread.scheduleWithRelativeAndState`](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/concurrency/currentthreadscheduler.js)

**Comment by benjamingr** [comment]
This should give you a general idea. https://github.com/petkaantonov/bluebird/blob/v2.9.9/src/util.js#L22-L39

**Comment by mattpodwysocki** [comment]
@benjamingr yes, I've tried that but it seems that it caused more of a performance regression than an actual gain due to the number of `.call` and `.apply` calls required.  That and I'm not often throwing which is the more expensive operation.

**Comment by benjamingr** [comment]
The problem with `try/catch` isn't that `throw`ing is slow - it's that the JIT can't optimize the whole function as soon as it contains a try/catch from what I remember.

**Comment by mattpodwysocki** [comment]
@benjamingr but that only holds true for V8 I believe.  Chakra optimizes for these calls as does SpiderMonkey I believe.

**Comment by benjamingr** [comment]
Maybe, I haven't read the Chakra source yet :) 

When running RxJS on the server performance is more of a big deal than running it on the client (at least for me).  At the moment the only viable (at least for me) server side platform for that runs V8 which does not optimize those calls. Having a faster RxJS would go a long way and open up a lot of possibilities - being able to do one (or several) observables per request (for reading the body for example - instead of node streams) could be really nice.

**Comment by mattpodwysocki** [comment]
@benjamingr making some changes right now where you should see some perf gains on the latest node.js.

**Comment by mattpodwysocki** [comment]
@benjamingr feel free to run it versus the old version and let me know of the results.

**Comment by benjamingr** [comment]
Thanks a ton! I'll do that when I get to work (I'm in Israel so work here is Sunday-Friday)

**Comment by mattpodwysocki** [comment]
Closing as per making the perf changes
