### ISSUE TITLE
Synonym for Rx.Observable.prototype.toArray()

### ISSUE THREAD

**Issue by dwoldrich** [Reactive-Extensions/RxJS#600]
When I use Rx.Observable.prototype.toArray(), I'm collecting the elements of the source observable sequence.  It's a nice way to wait for the source observable to complete and then work with the aggregate.  

I think it would be useful to have a synonym for toArray() called Rx.Observable.prototype.collect() 

Also, I like to follow toArray() with flatMap() too to synchronize and return the values.  If you like my collect() synonym, I suggest it would also be a useful shorthand to have a flatCollect() that combines the two operations.

**Comment by mattpodwysocki** [comment]
@dwoldrich I think that word `collect` is rather overloaded.  In the Ruby community `collect` is already used as an alias for `map` and since we have RxRuby, we already have that in there.  I'd rather keep consistency across libraries so that `collect`.  In addition, underscore and lo-dash use [`collect`](http://underscorejs.org/#map) as an alias to `map` as well.  So, making `toArray` aliased to `collect` would just confuse users coming from other libraries.

**Comment by dwoldrich** [comment]
Thank you for responding.  I wondered if there might be a collision in some context that would make such a addition difficult.

I searched the thesaurus for alternative synonyms, and "gather()" also describes what toArray() does.  Please consider that as well.

Philosophically speaking, is toArray() a part of the API that your team wants to discourage in general use because it blocks until its source Observable is completed?  That blocking semantic is really interesting and powerful in some contexts, but I can imagine how it might be abused in the wrong hands.  

My mind drifts towards searching for (and learning how best to choose from) polar opposites in API's.  I am still learning how to apply RxJS, and I considered how hotObservable.flatMap() would be a yin to a coldAndCompletedObservable.toArray().flatMap() yang, if you take my meaning.  And, how tidy would it be to have a complement to flatMap() expressed alongside in the API documentation:  something like a "flatToArray()" or "flatGather()".
