### ISSUE TITLE
expand's selector is executed after disposal.

### ISSUE THREAD

**Issue by jooyunghan** [Reactive-Extensions/RxJS#623]
I guess that if I take(1) from the expanded observable the selector should not be called because there's no need to expand anymore. Following code is slightly modified from the document's example code. The current behaviour does one more unnecessary expanding. 

    var source = Rx.Observable.return(42)
        .expand(function (x) {
          console.log("this should be not printed");
          return Rx.Observable.return(42 + x);
        }, Rx.Scheduler.timeout)
        .take(1);

    var subscription = source.subscribe(
        function (x) {
            console.log('Next: ' + x);
        });

prints

    Next: 42
    this should be not printed

**Comment by mattpodwysocki** [comment]
@jooyunghan I think you are confused about side effects and RxJS.  The `selector` call from the `expand` function will be called regardless as it does not know downstream only to take 1 via your `take(1)` call.  So, the call will be invoked, now it is a question of whether the `Rx.Observable.return(42 + x)` will ever be subscribed to.

Let's put this another way, let's try putting a `defer` call around the `console.log` call to prove that only the side effect of creating the Observable will happen.

```js
var source = Rx.Observable.return(42)
    .expand(function (x) {
      console.log("this should be printed");

      return Rx.Observable.defer(function () {
        console.log("this should be printed");

        return Rx.Observable.return(42 + x);
      })

    }, Rx.Scheduler.timeout)
    .take(1);

var subscription = source.subscribe(
    function (x) {
        console.log('Next: ' + x);
    });
```
Now, what would you expect to happen here?  Well, the side effect should always happen, because, remember, the expand selector will always get called.  It's just a matter of whether anything is done to the contents of the return that is the issue.

This therefore now prints:
```bash
λ node testbed.js
Next: 42
this should be printed
```

This is expected behavior and happens when you mix side effecting code with pure streams.  You need to be careful when doing so and also understand when things are executed.

**Comment by jooyunghan** [comment]
Thank you for clarification.
