### ISSUE TITLE
Replay buffer size seems not working

### ISSUE THREAD

**Issue by ivan-kleshnin** [Reactive-Extensions/RxJS#624]
```javascript
var Rx = require("rx");

var source = Rx.Observable.interval(1000).replay(1).refCount();

source.subscribe(createObserver('A'));

setTimeout(function() {
  source.subscribe(createObserver('B'));
}, 5000);

function createObserver(tag) {
  return Rx.Observer.create(
    function(x) {
      console.log(tag + ": " + x);
    });
}
```

Result:
```
A: 0
A: 1
A: 2
A: 3
B: 0 // B receives ALL values
B: 1 // !
B: 2 // !
B: 3 // !
A: 4
B: 4
```

Shouldn't `.replay(1).refCount();` behave the same as `.shareReplay(1)`. With the last I get correct

```
A: 0
A: 1
A: 2
A: 3
B: 3 // B receives one last value
A: 4
B: 4
```

**Comment by mattpodwysocki** [comment]
@ivan-kleshnin this is because you are using [`replay`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/replay.md) wrong.  It should be simply `replay(null, 1)` because the selector should be null.  We should probably have `shareReplay` and `replay` have the same signature, but that's another bug.
