### ISSUE TITLE
`ControlledObservable#request` method not propagated after other operators

### ISSUE THREAD

**Issue by int3h** [Reactive-Extensions/RxJS#644]
When transforming a `ControlledObservable`, the `request()` method is not included in the new `Observable` returned by the transform.

For example, with a `flatMap()`, we can't do something like:

```JavaScript
var controlledSource = Rx.Observable.from([1, 2, 3, 4]).controlled();
var transformedSource = controlledSource.flatMap(function(x, i, o) {
        return Rx.Observable.just(x);
    });
transformedSource.request(1);    // Error: no method 'request'
```

While this makes sense from an implementation standpoint (`transformedSource` is actually a `MergeAllObservable`, not a `ControlledObservable`), however it seems confusing semantically, since the transformed Observable is still controlled.

Because of this, we need to save a reference to the Observable just after applying `controlled()` on it, without applying any additional operators. If we want to transform the `ControlledObservable`, we do that on the saved reference. Any consumers who want both the transformed sequence and the ability to control it need to be passed both Observables.

So, while it may not be an outright bug, it is a case of confusing semantics.

**Comment by paulpdaniels** [comment]
I agree that it is painful to have to break up your nice clean chains to grab the reference, but I think this makes more sense then the alternative.  

For one, in your example it is really clear to the clients what you are actually requesting, however it is very easy to imagine a situation where the downstream clients are so far removed that they have no context for what is being passed to them.  One easy confusion would be, what am I really requesting from, a single item from the flatMap'd stream or its parent? And what happens if I add a `publish()` do I need to pass on the `ConnectableObservable` as well (Or even worse if I add a second `controlled()` )?  

Second, I don't see a problem with passing separate arguments for view and control, the better to enforce separation of concerns.

**Comment by mattpodwysocki** [comment]
@int3h agreed with @paulpdaniels on this one.  The controlled must be at a certain choke point as it were.  In the rewrite in RxJS 3.0, we can have request(n) on each subscription, but we're not going there right now.
