### ISSUE TITLE
Delaying a throw

### ISSUE THREAD

**Issue by khoomeister** [Reactive-Extensions/RxJS#648]
Firstly, is there a nice way to delay an observable that may possibly throw immediately?

```
var source = Rx.Observable
  .throw('test')
  .delay(1000)

// note: does not wait 1 second to throw
```

Secondly, maybe this page should be updated to mention that delay won't delay an error:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/delay.md

**Comment by paulpdaniels** [comment]
Perhaps not the most efficient system, but would this work for you?

```javascript

var source = Rx.Observable
  .throw('test')
  .materialize()
  .delay(1000)
   //Somewhere later
  .dematerialize()

```

**Comment by mattpodwysocki** [comment]
@khoomeister I think @paulpdaniels has the closest answer as none of the `delay` methods, whether it be `delay` or `delayWithSelector` will delay an error, only delays `onNext` and `onCompleted` calls.  You can get around this by calling `materialize` which is exactly what `delay` does in the first place so that you can view all messages regardless of whether it is an `onNext`, `onError` or `onCompleted` call.

**Comment by khoomeister** [comment]
OK awesome thanks guys :smiley:
