### ISSUE TITLE
Browser version and testing

### ISSUE THREAD

**Issue by erykpiast** [Reactive-Extensions/RxJS#673]
I encountered a wrinkle when I was trying to use `rx.virtualtime` and `rx.testing` modules with Browserify. As I found, [since last month](https://github.com/Reactive-Extensions/RxJS/commit/642d28e7891f10004ede563d57521eca1dce81aa) `package.json` contains `browser` field that sets main file to `dist/rx.all.js`. I can't find related bug, so I don't know why it was done, but apparently this feature collides with usage of testing and virtualtime modules. Internally they requires file `./rx`, not `./rx.all`, so when I try to fetch them like that in main test file:

```javascript
    require('rx/dist/rx.virtualtime'); 
    require('rx/dist/rx.testing');
```

and later on in my application

```javascript
    var Rx = require('rx');
```

I have two copies of Rx library in my bundle: one from `dist/rx.all` file and one from `dist/rx` file, Moreover, Rx required by `require('rx')` doesn't contain functions from virtualtime and testing modules. When I explicitly require `rx.all` (`require('rx/dist/rx.all`)`) it works as expected. But to use it for testing my code, I have to replace Rx dependency in each module with 'rx/dist/rx.all', what isn't really comfortable.

I don't know so far if it's a question or bug report. I would like to know how to use `rx.testing` and `rx.virutaltime` with Browserify. As a quick fix I removed `browser` field from `package.json` in my local copy of Rx and it works perfectly.

**Comment by sirbarrence** [comment]
I'm having the same issue and removing the `browser' key seems to fix. But this also means that the rx.testing code will end up in the production app bundle where it's not necessary. I only need to load rx.testing for karma tests. 

It might be easier if rx-testing were a separate npm module like rx-node and rx-dom.

**Comment by erykpiast** [comment]
What do you think about creating something like `browser-index.js`? It can contain similar code to `rx.js`, but without testing modules:

```javascript
var Rx = require('./dist/rx');
require('./dist/rx.aggregates');
require('./dist/rx.async');
require('./dist/rx.backpressure');
require('./dist/rx.binding');
require('./dist/rx.coincidence');
require('./dist/rx.experimental');
require('./dist/rx.joinpatterns');
require('./dist/rx.sorting');
// require('./dist/rx.virtualtime');
// require('./dist/rx.testing');
require('./dist/rx.time');

module.exports = Rx;
```

**Comment by sirbarrence** [comment]
Could you give an example of how a `browser-index.js` would be used? I'm not sure I follow.

I've found a decent workaround for my environment by adding some prebundle code to my browserify config in karma.conf:

```javascript
  browserify: {
    debug: true,
    transform: ['browserify-shim'],
    configure: function(bundle) {
      bundle.on('prebundle', function() {
        // Exclude rx.all.js since it does not include rx.testing.js
        bundle.exclude('rx/dist/rx.all.js');
        // Map `require('rx')` calls to the non-dist version of rx that does include
        // rx.testing.js.
        bundle.require('rx/index.js', { expose: 'rx' });
      });
    }
  },
```

If you're not using karma to run your tests, you might still be able to do the same thing with the browserify API in gulp or grunt config or do something similar with the browserfiy CLI args `--exclude` and `--require`.

Obviously I would prefer to have this "just work" out of the box instead of having to do the prebundle switcheroo, but this at least doesn't require me to modify rx's package.json. I can think of two possible long-term fixes:

- Remove `require('./dist/rx.testing');` from `rx/index.js`, change `./dist/rx.testing.js` to `require('rx')` instead of `require('./rx')`, then test code just has to `require('rx/dist/rx.testing')` to get the extra functionality added to Rx.
- Move `rx.testing.js` into a separate node module. Test code inside and outside the Rx project would need to list it as a `devDependency` and `require('rx-testing`)` to get the testing functionality.

I am not familiar enough with the big picture for this project to know whether either of those are good ideas or if they might have other undesirable ramifications.

**Comment by erykpiast** [comment]
I guess, both solutions you proposed can work for me! I'm only not sure if with the first one we don't fall into dangerous circular-dependency abyss...

Regarding `browser-index.js`. I was wondering if it's possible to create such file next to `index.js` and point to it in `package.json`, like that:

```json
"browser": {
  "main": "browser-index.js"
}
```
That's all, pretty simple and straightforward solution, I think, doesn't require modifications in infrastructure (no separated NPM module) nor in any file (you have not to change any paths anywhere).

**Comment by mattpodwysocki** [comment]
Fixed as per adding tests to all file
