### ISSUE TITLE
Rx.spawn doesn't work

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#700]
Hello @mattpodwysocki. I tried use this example, but this example doesn't work:

```js
var source = Rx.spawn(function* () {
    yield Observable.just(1);
    yield Promise.resolve(2);
    yield 3;
})();

var subscription = source.subscribe(
    function (x) {
        console.log('Next: %s', x);
    },
    function (err) {
        console.log('Error: %s', err);
    },
    function () {
        console.log('Completed');
    });
```

**Comment by xgrommx** [comment]
This isn't actually. I got it.

**Comment by mattpodwysocki** [comment]
@xgrommx I see your point as libraries such as [co](https://www.npmjs.com/package/co) return promises.  I'll work on getting that in there for the next release.

**Comment by xgrommx** [comment]
@mattpodwysocki I proposed pull request to co but it was rejected https://github.com/xgrommx/co/blob/master/index.js#L121. Reason - an observable isn't standard yet.

**Comment by jaawerth** [comment]
What is the expected behavior, though? Does Rx work at all? The docs have the example in the OP and suggest rx.spawn returns an observable, but this doesn't seem to be the case - it returns undefined for me and doesn't execute at all if I use Rx.Observable.just in the first yield, and if I remove that and try yielding promises or values I get the following error, regardless of what it tries to return:

```
  'use strict';
var Rx = require('rx');

var gen = Rx.spawn(function* () { 
  var r1 = yield 1;
  var r2 = yield 2;
  console.log('running');
  console.log(r1, r2);
})();

var source = gen();

```

Error (running the above in either a node environment with regenerator, or in iojs):
```
/home/jesse/rxtest/node_modules/rx/dist/rx.async.js:59
    if (isPromise(obj)) { return promiseToThunk(obj); }
        ^
ReferenceError: isPromise is not defined
    at toThunk (/home/jesse/rxtest/node_modules/rx/dist/rx.async.js:59:9)
    at next (/home/jesse/rxtest/node_modules/rx/dist/rx.async.js:205:21)
    at /home/jesse/rxtest/node_modules/rx/dist/rx.async.js:171:7
    at Object.<anonymous> (/home/jesse/rxtest/rxtest.js:11:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)

```
