### ISSUE TITLE
Rx Observable from an object

### ISSUE THREAD

**Issue by xgrommx** [Reactive-Extensions/RxJS#704]
Hello everyone. Anyone have experience use Rx with objects? Like so:

```js
Rx.Observble.from({a: 1, b: 2}).subscribe(console.log.bind(console));
```

Also I need something like that https://github.com/baconjs/bacon.js#bacon-combinetemplate. But In Rx this operator doesn't exists.

**Comment by paulpdaniels** [comment]
To the first part of your question use `Observable.pairs()` instead of `from()` for objects (note the documentation page is currently missing from the main docs, so you'll have to go [here](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/pairs.md).

To the second, will `combineLatest()` or `withLatestFrom()` not work? They appear to be about the same minus some syntactic sugar.

**Comment by mattpodwysocki** [comment]
@xgrommx yeah, `pairs` is the right operator to use as `from` requires an array-like object with a `length` property.  I will update the docs to include pairs.

**Comment by mattpodwysocki** [comment]
@paulpdaniels where is `pairs` missing from our documents?

**Comment by paulpdaniels** [comment]
Whoa, apparently I need more sleep, I was staring right at them. False alarm I guess.

**Comment by xgrommx** [comment]
Thanks! @mattpodwysocki What about ```Bacon.combineTemplate```? Rx has alternative for it? Also I create some interesting example for ```Rx.Observable.partition``` http://xgrommx.github.io/rx-book/content/core_objects/observable/observable_instance_methods/partition.html. Also @mattpodwysocki could you please look on this pull request https://github.com/Reactive-Extensions/rx.angular.js/pull/78 (Sorry offtopic)

**Comment by xgrommx** [comment]
I found it https://github.com/ahomu/rx.observable.combinetemplate. This is awesome =)

**Comment by paulpdaniels** [comment]
So....closed?
