### ISSUE TITLE
Implementing my own operators

### ISSUE THREAD

**Issue by shinyaohira** [Reactive-Extensions/RxJS#730]
I want to implement my own operators by applying a particular set of existing RxJS operators to it. Is there a function like `compose()` in RxJava? I think it's useful.

**Comment by paulpdaniels** [comment]
I believe that is only necessary in Java because of the static typing.  Javascript has no such limitations. If you want to create your own operators you can just add them to the Observable function prototype.

Using the example provided in the [article](http://blog.danlew.net/2015/03/02/dont-break-the-chain/) provided for why to use compose here is how you would do it in Javascript:

```javascript

Rx.Observable.prototype.applySchedulers = function(observeScheduler, subscribeScheduler) {
  return this.observerOn(observeScheduler).subscribeOn(subscribeScheduler);
};

Rx.Observable.from(someSource)  
    .map(data => manipulate(data))
    .applySchedulers(Rx.Scheduler.timeout, Rx.Scheduler.default)
    .subscribe(data => doSomething(data));

```

**Comment by shinyaohira** [comment]
So should we export the prototype object of ObservableStatic in rx-lite.d.ts? I'm using TypeScript and I get the following error:
```
Property 'prototype' does not exist on type 'ObservableStatic'.
```

**Comment by XeniaSiskaki** [comment]
I still get the same error mentioned by @shinyaohira  using v4.1
