### ISSUE TITLE
The Road to 3.0

### ISSUE THREAD

**Issue by mattpodwysocki** [Reactive-Extensions/RxJS#746]
All:

We're working towards RxJS version 3.0.

We have the following goals:
- Create minimal Observable implementation
- Remove all deprecated methods
- Create modular system so that you can pull in what you need
- Minor method signature changes

## Create Minimal Observable Implementation

There has been a bit of a demand for a minimal viable implementation of RxJS Observables so that others can interoperate with RxJS.  To that end, we will implement `rx.core.js` which will contains the minimal implementation of RxJS to only include `Observable`, `Observer` and `Observable.create` so that other libraries such as AngularJS can take advantage of RxJS.  

Then we will have another library called `rx.core.binding.js` which has all the `ConnectableObservable` methods with `publish` and `refCount`.  This requires bringing in the `ConnectableObservable`, but also the subjects including `Subject`, `AsyncSubject`, `BehaviorSubject` and `ReplaySubject`.

## Removing Deprecated Methods

The following methods will be removed from RxJS for version 3.0:
- `aggregate` - use `reduce`
- `catchException` - use `catch` or `catchError`
- `createWithDisposable` - use `create`
- `finallyAction` - use `finally` or `ensure`
- `returnValue` - use `just` or `return`

The following aggregation methods may have their behavior changed instead of throwing an exception if not found, will return undefined to match ES semantics such as `Array.prototype.find`
- `first` - `firstOrDefault`
- `last` - `lastOrDefault`
- `single` - `singleOrDefault`

## Create modular system ##

To help developers only pull in what they need, we have gone the direction that was taken previously by the lodash team to provide a way to bring in only the methods you want at any given time.  It is in the early stages and you can follow the progress in the [`src/modular`](https://github.com/Reactive-Extensions/RxJS/tree/master/src/modular) folder.  Help is wanted so please feel free to chip in!

## Changing method signatures ##

There are some oddities that need to be fixed with version 3.0 including:
- `fromEvent`
- `scan`

### Scan Method Changes

In previous versions, the seed came first followed by the accumulator:
```js
Observable.prototype.scan = function (/*seed, */ accumulator);
```

This has been changed to follow in the standard of `reduce` which has:
```js
Observable.prototype.scan = function (accumulator /*, seed */);
```

### FromEvent Method Changes

The `fromEvent` method has also changed.  Instead of passing in the arguments from the event callback, now the arguments will be as natural as the callback you would expect to use.

Previously, you had to do the following:

```js
var EventEmitter = require('events).EventEmitter;
var Observable = require('rx').Observable;

var e = new EventEmitter();

Observable.fromEvent(e, 'data', function (args) { return { foo: args[0], bar: args[1] }; );

e.emit('data', 'foo', 'bar');
```

Now can be simply can be written as such:
```js
var EventEmitter = require('events).EventEmitter;
var Observable = require('rx').Observable;

var e = new EventEmitter();

Observable.fromEvent(e, 'data', function (foo, bar) { return { foo: foo, bar: bar }; );

e.emit('data', 'foo', 'bar');
```

**Comment by xgrommx** [comment]
+1 :thumbsup:

**Comment by xgrommx** [comment]
I have one question about a new version on Rx. This project is similar or not https://github.com/trxcllnt/RxJS-2016

**Comment by mattpodwysocki** [comment]
@xgrommx that is a different project as they are experimenting on what RxJS vNext may be.  This is the current and ongoing RxJS.

**Comment by trxcllnt** [comment]
@xgrommx That is my initial work on a version of RxJS that targets the [ES2016 Observable spec](https://github.com/zenparsing/es-observable). The project is a collaboration between members of the Netflix's UI Platform and Google's Angular teams.

We are primarily concerned with meeting the needs of in-flight projects at Netflix and Google, but we hope this work benefits the wider Rx audience as well. Some of our goals include:
- Writing in TypeScript to keep Rx environment agnostic and ES2015 future-proof
- Make Observers conform to the ES2015 Generator spec
 - rename `onNext`, `onError`, and `onCompleted` to `next`, `throw`, and `return`.
 - `next` returns an iteration result (`{ value: Any, done: Boolean }`)
- Preserve the Observable type through the operator chain (e.g. `publish().select()` returns a `ConnectableObservable`)
- Hitting our strict performance goals by
 - implementing operators in terms of Observers instead of Observables
 - selectively applying try-catch only to user-provided functions to maximize throughput
 - removing the Immediate Scheduler in favor of iterative loops (made possible when `next` returns an iteration result)
 - switching the CurrentThread Scheduler queue to an Array or LinkedList stack
 - tracking disposables returned from scheduled actions
 - recursively scheduling actions without creating intermediate closures and disposables

That's the gist of what we've come up with so far. If we succeed, we hope to contribute back to the larger community with @mattpodwysocki's help. The [project](https://github.com/ReactiveX/RxJS) is currently being tracked under the same [ReactiveX](https://github.com/ReactiveX) organization as most of the other OSS Rx ports, like RxJava. @blesh is currently porting my project to TypeScript, which will give us a foundation to continue working from.

Best,
Paul

**Comment by xgrommx** [comment]
@mattpodwysocki @trxcllnt Thanks! As I guess Observable pattern is very promising.

**Comment by robertpenner** [comment]
Minor typo: 
`require('events)` 
(two places)

**Comment by danylaporte** [comment]
I think it's good news to see this framework evolve and gets more performant. I wish the next version of javascript contains the observable pattern built-in. I have personally rewriten rxjs in a more performant way and it's quite possible to increase radically the performance of what it is right now.

[asyncplify](https://github.com/danylaporte/asyncplify/tree/master/perf)

Continue your good work!
Regards,
Dany

**Comment by blesh** [comment]
@danylaporte that's a little comparing apples and oranges. I'm sure Asyncplify is a clever implementation of a streaming library, but it doesn't appear to be a comprehensive solution, and doesn't cover all of the cases that RxJS currently does.

To quote Yoda, "There is no try".

There is no error handling to speak of in asyncplify. For example a user-supplied projection method used [here](https://github.com/danylaporte/asyncplify/blob/ab8b9cbf4585b219de2c65b129a018a77005e6d5/src/map.js#L16} is never checked for an exception, and thrown errors in that mapping function are never sent down an error path. There also isn't a very robust scheduling story to that library. Current RxJS is far from perfect, but is built on a lot of hard work and usage, and has more cases covered. Covering those cases means a reduction in performance. Simply adding a try/catch block to a function causes it to deoptimize in V8.

**Comment by danylaporte** [comment]
@blesh you are right. This is not a mature lib as RxJS.

For the try / catch that deoptimize in V8, this is exactly why I did not used a try catch. What could be used instead is a opt-in approach where you can specify to use a try / catch on specific operations. In many case, the try / catch is superflous because the function is safe.

Regards,
Dany

**Comment by fdecampredon** [comment]
Sorry If I missed the info, I was quite busy these past months, does https://github.com/ReactiveX/RxJS is deprecated ? 
Also won't you conform to the https://github.com/zenparsing/es-observable observable spec ? 
Having observer respect the generator interfaces seems really important

**Comment by robertpenner** [comment]
@danylaporte Probably opt-out would be better.

**Comment by blesh** [comment]
@fdecampredon The ReactiveX/RxJS repo is new development... Right now centered in the typescriptify branch. It's not deprecated.

**Comment by mattpodwysocki** [comment]
@robertpenner correct, opt out is easy to do, in so much so that we could create an `unsafeMap` which could pass in the `observer` into the selector function so that if there is an error, then you could publish it yourself with `observer.onError(error)`

**Comment by donaldpipowitch** [comment]
Should `flatMapWithMaxConcurrent` work? This issue is referenced in its commit. I get

````
/rx/dist/rx.experimental.js:543
    return new FlatMapObservable(this, selector, resultSelector, thisArg).merg
               ^
ReferenceError: FlatMapObservable is not defined
````

**Comment by deadbeef84** [comment]
I have the same issue as @donaldpipowitch, when using it as a node module.

**Comment by mattpodwysocki** [comment]
@donaldpipowitch @deadbeef84 it should be fixed as part of 4.x
