### ISSUE TITLE
Question: how to combine sequences into a pipeline

### ISSUE THREAD

**Issue by dypsilon** [Reactive-Extensions/RxJS#767]
Hello RxJS Team!

I have to implement a pipeline of sequences where the first sequence pushes the events into the next sequence and so on, until the last sequence emits the events on the main pipeline. This is not "concat", because I don't want to have the data from all the sequences on the main pipeline, only the results. 

[stream-combiner2](https://www.npmjs.com/package/stream-combiner2) solves this use case for node.js streams
[Gulp](http://gulpjs.com/) operates this way, either.

How do I solve this with RxJS? I couldn't find any simple solution.

**Comment by paulpdaniels** [comment]
Do you have a specific example to address? This is a pretty generic behavior for Rx.

**Comment by dypsilon** [comment]
I have to admit, it is a pretty generic question. It is hard to find an isolated example because it would require quite some code to make any sense. 

Here is an example of a [gulp](http://gulpjs.com/) pipeline. It is a JavaScript bundler for CommonJS modules. It takes an array of [globes](https://en.wikipedia.org/wiki/Glob_(programming)) and returns a stream of a bundled JavaScript file which is streamed directly to the browser or into a file, depending on the context. I would like to replace it with Rx:

~~~javascript
return StreamArray(collectSpecs()) // gets an array of globes and converts it into a stream of file names
  .pipe(resolveGlobes())  // resolves the globes and loads the files from disk
  .pipe(determineIds())  // determines the module id using the file name (for each file)
  .pipe(inspectShort())  // prints some debug output (for each file)
  .pipe(wrap())  // adds a wrapper around the code to make it loadable (for each file)
  .pipe(Concat('bundle.js')) // concatenates everything into a single stream
  .pipe(VinylToStream()) // converts the vinyl-fs stream to a normal buffered stream
  .pipe(finish(startTime)); // prints the benchmark
~~~

The idea here, off course, is that the function in between are all reusable. ResolveGlobes, Concat, VinylToStream are all used for a similar CSS pipeline and can be reused elsewhere.

The only building block I'm lacking right now is the ability to "pipe" one sequence into the next. The aforementioned code is only one example, this pattern is useful in many places and I have a couple of other tasks, I would like to structure this way, already.

I suppose, the final code could look something like [forkJoin](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/forkjoin.md), but instead of collecting the last values it would connect/pipe the subjects (?).

**Comment by paulpdaniels** [comment]
I can't say I am terribly familiar with pipes, but from an RxJS position every operator you chain on the end will receive each value emitted from the previous operator
The example you gave would likely be composed of several operators (this is very pseudo-y, but hopefully it gives you an idea):

```javascript

return Rx.Observable.fromArray(collectSpecs()) //gets an array and converts it into an observable of file names
  .flatMap(function(fileName) { return loadFileObservable(fileName); }, 
           function(fileName, file) { return {fileName : fileName, data : file}; })
  .map(determineId) //Would add a field for the moduleid per file
  .tap(inspectShort) //prints some debug output (for each file)
  .map(wrap) //Wraps the data
  .reduce(concatFiles, {}) //Receives all files and then emits a single aggregate message
  .timeStamp() //Adds a timestamp value to the emitted value
  .subscribe(finish);

```

**Comment by dypsilon** [comment]
@paulpdaniels thank you for your answer. In my understanding RxJS works by chaining the operators together instead of using the generic pipe method. The "piping" happens inside the operators. I think it could work similarly to my example above, because the functions could be reused, still.

If nobody else has an opinion on this I would close the ticket.

In my opinion it would be really great to have this feature in RxJS, though. Pipe two or more observable (or subjects) together. It would allow for better composition of complex flows.

~~~JavaScript
var process1 = Rx.Subject.create();
var process2 = Rx.Subject.create();
var resultingProcess = Rx.Subject.create();

var pipeline = Rx.Observable.pipe(
    Rx.Observable.range(0, 10),
    process1,
    process2,
    resultingProcess 
);

var subscription = pipeline.subscribe(
    function (x) {
        console.log('Next: ' + x);
    },
    function (err) {
        console.log('Error: ' + err);
    },
    function () {
        console.log('Completed');
    });
);
~~~

Do you think it would make sense to implement it? How hard, in your opinion, could it be to add such a feature?

**Comment by erykpiast** [comment]
:+1: for the idea. I always have the same issue with promises. But it is possible that I don't get something and can't see straightforward solution.

**Comment by paulpdaniels** [comment]
@dypsilon I still don't see what that format provides you that direct chaining doesn't. Additionally, there simply is no way to do this with Observables (since they don't have an `onNext`), it would _have_ to be a Subject, and even then it would require extra work. Either you need to create a subject from an Observable/Observer factory method, or you would need to pass in a paired Subject/Function, the latter of which would apply the transform on output, and in that case you would still resort to chaining.

That being said, implementation itself would not be terribly hard.  Beneath the scenes it would just iterate through the arguments and hook up the argument chaining. But I personally do not think it makes sense to add this as a feature.

@erykpiast `flatMap` is your friend, the selector function accepts promise return values implicitly.

**Comment by dypsilon** [comment]
@paulpdaniels could you provide an example of direct chaining?

This format would give me a general framework for composing and reusing my functions. The output contract of observables is very strict: onNext, onError, onCompleted. But the input format from the previous operator is not defined. It's sometimes a simple value, another times its two or three values. That requires another wrapper function to build a pipeline using operators. Such framework would provide a simple contract for input and output.

But then again, maybe I just don't have enough experience and try to migrate concepts from node streams which are unnecessary in Rx.

**Comment by erykpiast** [comment]
@paulpdaniels, I meant chaining Promises in functional way. I know the trick with `flatMap` :)

**Comment by paulpdaniels** [comment]
@dypsilon Hmmm...I am sort of seeing your point, I think [transducers](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/transduce.md) might be what you are looking for.

**Comment by paulpdaniels** [comment]
@dypsilon also you could try looking at the rx-node project. If there truely is nothing comparable in Rx nothing stops you from building the stream as you normally would and then converting it into an observable stream

**Comment by dypsilon** [comment]
@paulpdaniels thank you for all your suggestions. I'm looking into transducers right now. I think they are the best answer to my question and I should have probably looked into them earlier.

I will close this ticket now, because there are probably no better solution inside the Rx ecosystem.

**Comment by shri3k** [comment]
Hey @dypsilon, did you ever figure out how to use the `pipe` like feature in `Rx`? I've been meaning to find a substitute for them myself. Basically, what I wanted to do was reuse some of the `transform` streams that `node` has and use it in Rx.  
I am at a point where I can listen to `readable` stream but I'm a little lost on how to write on `writable` stream in Rx. Essentially what `pipe` is doing is that it's writing from a source to a `writable` stream with some backpressure applied to it. I did take a quick look at this package called [rx-node](https://github.com/Reactive-Extensions/rx-node) which seems like a good starting point but I wanted to get your input first since you've stumbled on this same issue as I have. I'm also just starting to use Rx so I don't know if there's already a better solution to this.

**Comment by dypsilon** [comment]
Hey @shri3k, I started to use highland because of this feature. It's much easier.

**Comment by shri3k** [comment]
@dypsilon, so before giving `highland` a try I did an extensive search on whether this can be done in `Rx` or not and it seems that there has been previous attempts on bringing this feature.
Mentioned:- [here](https://github.com/Reactive-Extensions/RxJS/issues/353) and [here](https://github.com/Reactive-Extensions/RxJS/issues/469) and turns out there *is* infact a `pipe` function in `rx-node`. This is just a simple example but the underlying principle is the same.

```js
const fs = require('fs');
const rx = require('rx-node');

var str = fs.createReadStream('./dummyfile.txt', {
	'encoding': 'utf8'
});
var obs = rx.fromReadableStream(str);
obs.pipe(process.stdout);
```

I will give `highland` a try as well but I'm quite excited that this exists in `Rx` itself. :smiley:

**Comment by shri3k** [comment]
Follow up.  
I just realized that `pipe` returns a `stream` and not `Observable` and looking at the src of `rx-node` gives me an impression that `fromReadableStream` is just a wrapper on top of `stream` which is why the above works. 
Well, I'm not as excited as I thought I'd be now. :confused:

**Comment by nathan-alden** [comment]
I came across this GitHub issue when I was searching for a way to set up a pipeline with Rx. It sounds similar to what @dypsilon wanted to do: essentially, I want to emulate PowerShell's style of pipelining. I have an enumerable of elements in a queue. I dequeue an element and pass it to a handler. The handler may process the element, then either write something to the pipeline (maybe the element it processed, maybe something else, maybe multiple somethings) or write nothing (in which case the next handler in line will never be called for the original element). It doesn't seem like this is easily possible in Rx.

**Comment by xareelee** [comment]
@dypsilon and @shri3k, I just published an npm package called [gulp-on-rx](https://github.com/xareelee/gulp-on-rx/tree/master) which allow you to use gulp on the Rx way. You might be interested in it.
