### ISSUE TITLE
Use of Scheduler in Node?

### ISSUE THREAD

**Issue by daniel-shin1104** [Reactive-Extensions/RxJS#842]
Hello, first off great work!

I'm from the land of iOS where I've used [ReactiveCocoa](https://github.com/ReactiveCocoa/ReactiveCocoa) extensively and yet have recently ventured into the promised land of Node to refactor some of my server impl.

AFAIK, Node is single-threaded and mimics a concurrency model using its event loop through asynchrony. If so, what is the purpose of even having `Scheduler`? In RAC, `Scheduler` is essential to support UI update via main thread, dispatching work to background thread etc.

Also in the context of Node where no UI is involved, it seems of no use. I'm fairly new to this library so I might be missing some stuff here.

Please help! Thanks.

**Comment by paulpdaniels** [comment]
The most obvious one is probably the `TestScheduler`. If everything was simply using `TimeoutScheduler` then testing would be a huge nightmare, since your test code would be victim to the real world clock. For the `CurrentThreadScheduler` and `ImmediateScheduler` the benefits are perhaps not so obvious, but are good for things that need to happen immediately and don't incur the overhead of actually scheduling something on the event loop. Finally if you are getting really esoteric and you are doing something like replaying log values at 2x speed (which I have done) you might be interested in slotting in the `HistoricalScheduler` rather trying to compute time offsets by hand.

More generally, I think it is important to think of `Schedulers` not just as that thing you use when your application is throwing a `CrossThreadAccessException` but more as abstractions of your application's notion of time and in that regard they are just as important to a single threaded environment as to a multi-threaded.

**Comment by daniel-shin1104** [comment]
Aha! Thanks for the clarification. I never thought `Scheduler` as more than an abstraction over multi-threading worker. Seeing it from time-governing abstraction, now everything makes sense. Cheers!
