### ISSUE TITLE
fromNodeCallback behaves differently based on param count

### ISSUE THREAD

**Issue by tusharmath** [Reactive-Extensions/RxJS#861]
Looking at the code on this [line](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromnodecallback.js#L32)

```javascript
if (results.length <= 1) {
  o.onNext(results[0]);
} else {
  o.onNext(results); // why not: o.onNext.apply(null, results)
}
```
What is the rationale behind having such disparate behaviour based on the params? Its awfully confusing!

**Comment by mattpodwysocki** [comment]
@tusharmath because if the callback only has one value, eg `fs.stat` where it has the callback signature `function (err, stat)`, it makes sense that the `onNext` call will only bear the `stat`.  However, if there are callbacks with more than one parameter outside of the error, then it makes sense to give them all of the results in an array, if you didn't bother to give us a `selector`

**Comment by tusharmath** [comment]
@mattpodwysocki I feel its inconsistent, especially if you are working with a module which contains dynamic number of arguments. 

Consider modules such as [request](https://www.npmjs.com/package/request) which pass 3 parameters instead of 1 and then one needs to write a especial selector — `_.identity`, only for this case which is confusing for developers because now the whole story has to be explained to them also, as you explained above.

**Comment by mattpodwysocki** [comment]
@tusharmath all libraries do this that expect a single argument either with a selector or not with a selector such as Bluebird, async, and others.  This is consistent with other libraries and hasn't been confusing to their users.
