### ISSUE TITLE
subject not repeatable

### ISSUE THREAD

**Issue by Mosho1** [Reactive-Extensions/RxJS#882]
This snippet doesn't seem to work:

    var subject = new Rx.Subject();
    subject.repeat(2).subscribe(function(f){ console.log(f)})
    subject.onNext(2);

Only one '2' is logged.

**Comment by paulpdaniels** [comment]
You have a couple issues with your code. 

1. `repeat()` works by capturing the `onCompleted` message then resubscribing to the underlying `Observable`, you are never completing the subject so it will never repeat.

2. Even if you did you wouldn't see repeating behavior in this case because the `Subject` is a hot `Observable` that does not cache its values, so resubscribing after it completes is essentially meaningless.

Two fixes:

1. Use a `ReplaySubject` instead

   ```javascript

   var subject = new Rx.ReplaySubject();
   subject.repeat(2).subscribe(function(f) {console.log(f);});

   subject.onNext(2);
   subject.onCompleted();

   ```

2. Switch to a cold `Observable` that will re-emit values every time it is subscribed to

   ```javascript

   Rx.Observable.just(2).repeat(2).subscribe(function(f) { console.log(f); });

   ```

**Comment by Mosho1** [comment]
I see... thanks!
