### ISSUE TITLE
fromEvent to support `useCapture`

### ISSUE THREAD

**Issue by Frikki** [Reactive-Extensions/RxJS#897]
The `EventTarget.addEventListener(type, listener[, useCapture])` lets us specify if we want to initiate capture.

But it does not seem as `Rx.Observable.fromEvent(element, eventName[, selector])` supports this fundamental feature -- in Web development, a quite important feature to be able to access, for example, when dealing with events `focus`, `blur` and `change` that don’t bubble.

**Comment by mattpodwysocki** [comment]
@Frikki use [RxJS-DOM](https://github.com/Reactive-Extensions/RxJS-DOM) for `useCapture` as it makes more sense there with [`Rx.DOM.fromEvent`](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/fromevent.md). Since `Rx.Observable.fromEvent` is such a flexible event converter, `useCapture` is only used in one code path as it isn't required for Node.js, Angular, jQuery, etc.

**Comment by mattpodwysocki** [comment]
@Frikki closing as you should use a DOM library instead or wrap `fromEventPattern` yourself to do that as we want to keep fromEvent generic and not tied to the DOM

**Comment by Frikki** [comment]
@mattpodwysocki Yes. Sorry for not commenting back earlier. I agree.
