### ISSUE TITLE
fromPromise error in onNext

### ISSUE THREAD

**Issue by vekexasia** [Reactive-Extensions/RxJS#925]
Hello there,

I'm having inconsistent behavior when an error is triggered in the onNext callback and Rx.Observable.fromPromise is used such as:

```javascript
 Rx.Observable.fromPromise(
          new Promise((resolve, reject) => {
          resolve('antani');
          })
      ).subscribe(
          (r) => {console.log(r); throw new Error("erroooooor!");},
          (e) => {console.log(e); done();}
      );
```

if i switch to

```javascript
Rx.Observable.of(1)
      .subscribe(
          (r) => {console.log(r); throw new Error("erroooooor!");},
          (e) => {console.log(e); done();}
      );
```

the error is shown in console as uncaught exception while, when using fromPromise is not. 

This is causing issues when using `assert` within my async mocha tests. The error is catched somewhere in rxjs code (my guess) and so the test goes time-out.

**Comment by vekexasia** [comment]
I presume (I just started to get in touch with promises) that the current FromPromiseObservable should be changed from

```javascript
FromPromiseObservable.prototype.subscribeCore = function(o) {
      this.p.then(function (data) {
        o.onNext(data);
        o.onCompleted();
      }, function (err) { o.onError(err); });
      return disposableEmpty;
    };
```

to

```javascript
FromPromiseObservable.prototype.subscribeCore = function(o) {
      this.p.then(function (data) {
        o.onNext(data);
        o.onCompleted();
      }, function (err) { o.onError(err); })
      .catch(function(err){ o.onError(err) });
      return disposableEmpty;
    };
```

**Comment by paulpdaniels** [comment]
Problem is that I don't think that some `Promise` types support the `catch` syntax. [jQuery]() comes to mind. I think you are right though, the `.then(success, fail)` syntax is problematic since it won't catch errors thrown from `onNext`. At first glance I would think we need something more like:

```javascript

FromPromiseObservable.prototype.subscribeCore = function(o) {
  this.p.then(function(data) {
    var result = tryCatch(o.onNext).call(o, data);
    if (e === errorObj) {
      return o.onError(result.e);
    }
    o.onCompleted();
  }, function (err) { o.onError(err); });
}

```

**Comment by paulpdaniels** [comment]
Actually ignore my previous example, it won't work in this case because the AutoDetachObserver will dispose of the subscription before the `onError` can get propagated.

As a general rule we do not handle exceptions coming from observers `onNext` calls, `Promises` seem to present a special case simply because they won't allow an unhandled exception to propagate out of their scope.

**Comment by vekexasia** [comment]
@paulpdaniels your example looks fine to me... i don't see why AutoDetachObserver would not work....

**Comment by paulpdaniels** [comment]
@vekexasia, you can try it out yourself, the problem stems from the fact that you are throwing within the `onNext`, when that happens the ADO disposes of the subscription and then throws the exception up the chain. In normal practice this would result in eventually it hitting the top of the stack if no one was catching it. However, with promises it swallows the exception instead. We can retrieve it through a `onReject` handler but we can't push it to an `onError` handler because the subscription is already gone.

I'll take a deeper look at this when I have some time.

**Comment by mattpodwysocki** [comment]
@vekexasia what environment are you running this in?  Node seems to swallow the errors from Promises, however, I do get error reports from Chrome and Firefox using this simple code:
```js
var disp = Rx.Observable.fromPromise(Promise.resolve(42))
  .subscribe(function (x) {
    throw new Error();
  });
```

**Comment by blesh** [comment]
>  Node seems to swallow the errors from Promises, 

Are there specific versions of Node that do this?

**Comment by paulpdaniels** [comment]
@mattpodwysocki, @blesh , I guess the ES6 is really the standard on this then? Using native promises the throw occurs (only tried this on chrome, haven't bumped my node version yet), but the bundled RSVP library will swallow the exception and leave the test spinning. Seems kind of odd to me that the former just barfs up an error if there is no handler at the time of rejection, but I suppose that is inline with the synchronous version of throwing outside of a try/catch.

**Comment by blesh** [comment]
Try this:

```
FromPromiseObservable.prototype.subscribeCore = function(o) {
      this.p.then(function (data) {
        o.onNext(data);
        o.onCompleted();
      }).then(null, function(err) {
        o.onError(err);
      ]);
      return disposableEmpty;
    };
```

**Comment by blesh** [comment]
... actually no... the only way to get it to escape the suckage of Promise error handling is to schedule it to throw asynchronously.

```js
FromPromiseObservable.prototype.subscribeCore = function(o) {
      this.p.then(function (data) {
        o.onNext(data);
        o.onCompleted();
      }, function(err) {
        o.onError(err);
      })
      .then(null, function(err) {
        setTimeout(function() { throw err; })
      });
      return disposableEmpty;
    };
```

That's pretty gross

**Comment by blesh** [comment]
... but that means it'll throw outside of the block that is executing that made it throw to begin with. :\

**Comment by paulpdaniels** [comment]
@blesh certainly we might be able to spruce it up a bit by using a `Scheduler` but you are right not terribly pretty. The other option I was considering was if we don't have `FromPromiseObservable` implement `ObservableBase` so that we aren't forced to use an `AutoDetachObserver` so we could pass the error to the onError handler. But then we end up with inconsistent behavior with regards to other `Observerables` and if the stream is synchronous and the user is using the default handler I think it will still end up getting swallowed.

**Comment by paulpdaniels** [comment]
@blesh I think your proposal is the best in this case, though I would suggest that we support the use of `Scheduler`s in place of `setTimeout` so you example would be:

```javascript

FromPromiseObservable.prototype.subscribeCore = function(o) {
      var scheduler = this.s;
      var sad = new Rx.SingleAssignmentDisposable();
      this.p.then(function (data) {
        o.onNext(data);
        o.onCompleted();
      }, function(err) {
        o.onError(err);
      })
      .then(null, function(err) {
        sad.setDisposable(scheduler.scheduleFuture(err, 0, function(e){
          throw e;
        }));
      });
      return sad;
    };

```

**Comment by mattpodwysocki** [comment]
@vekexasia fixed as per https://github.com/Reactive-Extensions/RxJS/commit/3652801b566ecceb5f7798c0cc471762f92d8e6f

**Comment by vekexasia** [comment]
Hello @mattpodwysocki thank you. Is it in npm already?
