### ISSUE TITLE
Observable.prototype.shareReplay doesn't seem to disconnect when no more subscribers

### ISSUE THREAD

**Issue by elayman** [Reactive-Extensions/RxJS#927]
See jsbin: http://jsbin.com/migawaqeya/1/edit?html,js,console

Steps: 
1.Subscribe(sub1) to observable that has shareReplay enabled.
2.observable emits data(data1)
3. dispose subscription
4.Subscribe again(sub2) to observable that has shareReplay enabled
Expected: sub2 should only get future data, not data1
Actual: sub2 receives replay data1

**Comment by paulpdaniels** [comment]
@elayman It is working as expected, the refCount going to zero does not clear the `ReplaySubject`s buffer. All that happens when it disconnects is that the internal subscription is disposed of so the that the `ReplaySubject` stops receiving events. You can see that it disconnects if you try calling `onNext` between when you dispose the connection and when you subscribe to the next observer.
