### ISSUE TITLE
[regression] v4.0.0's TypeScript definition don't include Observable.prototype.zip().

### ISSUE THREAD

**Issue by saneyuki** [Reactive-Extensions/RxJS#932]
## environment

- RxJS v4.0.0
- At least, I confirm this regression in [rx.all.d.ts](https://github.com/Reactive-Extensions/RxJS/blob/d5a3691db5fe7e435881477b6e8649b4e0eadfb6/ts/rx.all.d.ts) and [rx.all.es6.d.ts](https://github.com/Reactive-Extensions/RxJS/blob/d5a3691db5fe7e435881477b6e8649b4e0eadfb6/ts/rx.all.es6.d.ts).

## actual

- v4.0.0's type definitions for TypeScript don't include `Observable.prototype.zip().`
   - They includes only `ObservableStatic.zip()`
- I think this is regression because:
  - this is not noted in [release note](https://github.com/Reactive-Extensions/RxJS/releases/tag/v4.0.0)
  - the original definition is still in this repository: https://github.com/Reactive-Extensions/RxJS/blob/146384d9943bd3b1e692a83f199a73c9e4a3d193/ts/core/linq/observable/zipproto.ts

**Comment by mattpodwysocki** [comment]
@david-driscoll is there a reason for this not being in the all, because I see zipproto.ts in there...

**Comment by david-driscoll** [comment]
Not sure!  I'll have a look tonight.

**Comment by baltie** [comment]
@mattpodwysocki  @david-driscoll  linq/observable/zipproto.js is not included in any concat target in Gruntfile.js any more. It used to be, but commit 5bacc78 changed that and replaced it with perf/operators/zip.js.

Because of that, zipproto.ts isn't included any more since it's corresponding js file is not a concat target. I'm not entirely sure what the proper fix is here. The rebuild-ts task depends on the names in perf/operators and linq/observable being unique regardless of location. If perf/operators/zip.js was renamed to perf/operators/zipproto.js, it would fix the TypeScript issue, but is that an acceptable change?

**Comment by saneyuki** [comment]
@mattpodwysocki 

[The release note](https://github.com/Reactive-Extensions/RxJS/releases/tag/v4.0.6) says this & #931 are fixed in `v4.0.6`, but the npm published archive don't include #970. `v4.0.6` is tagged to a1f10de40007e360d556e6efae5ac7e7af2b4b62 which is the previous commit before merging #970.
