### ISSUE TITLE
.find() does not returns undefinied if unfound

### ISSUE THREAD

**Issue by manuelfc1** [Reactive-Extensions/RxJS#939]
Trying the example from the docs:

		var array = [1, 2, 3, 4];

			var source = Rx.Observable.from(array)
				.find(function(x, i, obs) { return x === 5; });

			var subscription = source.subscribe(
				function(x) {
					console.log('Next: %s', x);
				},
				function(err) {
					console.log('Error: %s', err);
				},
				function() {
					console.log('Completed');
				});

it does not log "undefined" as expected

**Comment by paulpdaniels** [comment]
@manuelfc1 Looks like the docs are wrong here, per this commit 86787f89e29655305d3995a0b4bd0f075ab15735, `find` was fixed so that if no value is found it should just complete. I'm guessing this was changed because it is difficult to tell if the sequence is empty or you are just returning `undefined`.

But we should probably fix the docs either way.

**Comment by mattpodwysocki** [comment]
@manuelfc1 documentation fix coming, yes it defaults to `onCompleted` now if not found, not undefined.

**Comment by manuelfc1** [comment]
A CHANGELOG would be also appreciated :)

**Comment by mattpodwysocki** [comment]
@manuelfc1 document fix completed
