### ISSUE TITLE
fromEvent not firing in V4.0.1 at least with angularjs & angular-material

### ISSUE THREAD

**Issue by manuelfc1** [Reactive-Extensions/RxJS#957]
I'm using Observable fromEvent inside a very simple directive with angularjs and angular material,
everything goes well with V.4.0.0, but when I update to v.4.0.1 it does not work any more.

This is the link function of the angular directive:

link = (scope: IExtendedScope, ele: ng.IAugmentedJQuery, attrs: IExtendedAttrs) => {
			this.rx.Observable.fromEvent(ele[0], 'click')
                                 // bla bla bla
				.subscribe(
				(res: any) => console.log(res),
				(err: Error) => console.log(err),
				() => console.log('completed'));
});

**Comment by paulpdaniels** [comment]
So it's throwing an exception? Or the event is not firing? Could you build a simple jsbin/jsfiddle to reproduce the issue?

**Comment by manuelfc1** [comment]
The event is not firing at all.
The fact is that with 4.0.0 all went well, but not with 4.0.1.
I'll try to reproduce it later will a codepen

**Comment by manuelfc1** [comment]
Here is the codepen:

https://codepen.io/manuelfc1/pen/epRXaK

**Comment by Javiani** [comment]
>
The event is not firing at all.
The fact is that with 4.0.0 all went well, but not with 4.0.1.
I'll try to reproduce it later will a codepen
@manuelfc1, @paulpdaniels 

I'm learning RxJs right now and I was pulling the 4.0.1 from cdn, and yes... the fromEvent is not firing any events, I'm using plain javascript ( Vanilla ). It took some hours to realize that the problem was the version of the library, and not the implementation... My baby step wasn't working at all..

It fires events only if you're using jQuery...
I'll use 4.0.0, I just pass by to let you know about that issue.
